### ISSUE TITLE
Support for nested tags in the icon marker editor

### ISSUE THREAD

**Issue by jaroet** [esm7/obsidian-map-view#10]
I have the following snippet in the icon marker editor ... 

  "#person/family": {
    "prefix": "fas",
    "icon": "fa-user",
    "markerColor": "yellow"
  }

The works fine for me but beside person/family I have also a person/work tag and person/sport tag, and more ... . 

I would like to have all my person's with a location be shown on the map. So something like "#person/*" would be perfect but that does not seems to work. 

I could use multiple entries for all my different person/?? tags but is not an optimal solution. Would be great if you could support nested tags.

**Comment by esm7** [comment]
That sounds super useful. I'll do that.

**Comment by esm7** [comment]
Added in the new version :) You can now use `#person*` or `#person/*`.

**Comment by jaroet** [comment]
Thanks ... that works great 👍

**Comment by zhl111** [comment]
> Thanks ... that works great 👍


How does this work, please? My computer knowledge is very weak

**Comment by esm7** [comment]
In the Map View configuration, under "edit the marker icons (advanced)", any tag can have a `*` symbol to denote more characters: e.g. if you change `#trip` to `#trip*` it would also match tags like `#trip-to-hawaii`.
Note this is an advanced setting, it is currently not as user-friendly as I'd like it to be, and it's unfortunately too easy to get wrong.
