### ISSUE TITLE
FR: Support Inline tags

### ISSUE THREAD

**Issue by brimwats** [esm7/obsidian-map-view#102]
I have a note reading

```
- [Spartacus Books](geo:49.26705769880276,-123.06990416761172) #books
	- Google Maps [3378 Findlay St, Vancouver, BC V5N 4E7](maps://3378 Findlay St, Vancouver, BC V5N 4E7)
```

when I search `path:"100 - Personal/Canada Notes/Vancouver Recommendations.md" tag:#books` it does not show up

**Comment by esm7** [comment]
1. The query you entered is invalid, I seem to be missing an `AND` before `tag:#books`. Note that when the query is invalid, the query box should be red.
2. If you want the '#books' tag to be applied only to this geolocation, see the format for inline tags in the README. (using `#books` marks the complete note)

**Comment by brimwats** [comment]
that makes sense. sorry for the false alert!
