### ISSUE TITLE
Switch to a different tiles provider, as OpenStreetMaps does not allow using tiles from their server in any application.

### ISSUE THREAD

**Issue by dkapila** [esm7/obsidian-map-view#11]
OpenStreetMaps forbid using their tile servers (map APIs) in any other application, and it violates their requirements, since OpenStreetMaps's own server is meant as a demo environment. I see that there is an option to switch to another provider, but the default option of setting it to OpenStreetMaps should definitely be switched.

More details on their policies here: https://operations.osmfoundation.org/policies/tiles/. Maybe it's good to double check with them?

**Comment by esm7** [comment]
Thank you for pointing this out, I'll learn the topic and make any adjustments needed!

**Comment by kristofferR** [comment]
CartoDB Voyager is free, and really nice:

https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png

https://carto.com/blog/new-voyager-basemap/
