### ISSUE TITLE
Search feature not working 

### ISSUE THREAD

**Issue by rossoj85** [esm7/obsidian-map-view#111]
Search feature stopped working suddenly on Mac. Even famous cities coming up as "no results found"

**Comment by rossoj85** [comment]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/25422645/180692288-6c236459-85de-4936-90ac-00302346c588.png">

**Comment by olavarriaga** [comment]
Same Issue on my end. Until it is fixed I'm using 2.0.5 installed with BRAT.

**Comment by esm7** [comment]
1. Can any of you experiencing the issue open the Obsidian developer console (Ctrl+Shift+I) and copy any errors showing up there?
2. In the Map View settings, what do you have configured for "geocoding search provider"? And if you're using Google, do you have "Use Google Places for searches" turned on?

**Comment by rossoj85** [comment]
1. The error message is can't getSouthWest of null. 2. 

2. II am using openstreetmap as the search provider.  
<img width="348" alt="image" src="https://user-images.githubusercontent.com/25422645/180694667-93435ba6-86da-4f22-a42d-187498451803.png">

**Comment by esm7** [comment]
Released 2.1.1 that should fix this, please upgrade and let me know if that's indeed the case.

**Comment by rossoj85** [comment]
Fixed. Thanks so much for the quick response. Really enjoying the plugin!
