### ISSUE TITLE
Follow note issue and other improvements

### ISSUE THREAD

**Issue by Darkbluetest** [esm7/obsidian-map-view#113]
Hi

I have v0.15.9 of Obsidian and updated this plugin to 2.1.1, but I have several issue (or maybe it is just me):

1- When "Follow active note" is selected, the map fails to follow the note, it hides all the notes that are not the selected one, but if the note falls outside of current view, it does not change the view to center around it (I use Openstreetmap).

These ones are likely more improvements than "problems":

2- I see the blue glow around the map marker for a location, only when I search for it (using the magnification icon top right on the map), but not when using "follow active note" or a filter query
3- When "Follow active note" is selected, the other notes disappear, instead of being left visible in the map and just add glow to the selected one (I guess because it is a query/filter).

Thanks!

**Comment by esm7** [comment]
Regarding #1, what's your setting for "Map follows search results" from the settings pane?
If it is turned on, "follow active note" should move the map and not just filter the markers.

Regarding #2 and #3, this is currently the defined behavior. What queries of all types do (and for that matter "follow active note" is a query that is just updated automatically) is to filter the markers.
I wrote the highlight/glow implementation with the intent to expand it, and in the future allow queries to filter and queries to highlight, even with different color sets (e.g. have a query that filters the markers, on top of that a query that adds a blue glow, on top of that a different query that adds a red glow, etc.)
It's currently just in my wishlist, and would love to know if that's something users want.

**Comment by Darkbluetest** [comment]
"Map follows search results" is activated, I tried to disable and enable it, but no changes. The map do not move.

ok for the other features. Obviously, highlighting is something I presonally would use much more than the filter behaviour.

**Comment by esm7** [comment]
Do you mind to make a video showing the problem? I'm unable to recreate it no matter what I do, and I might be missing some detail that I didn't think to ask about.

**Comment by Darkbluetest** [comment]
Hi, I have done a short video with the testing vault I use normally, the "Turbine" note is the only that works as you will see at the end of the video.

https://user-images.githubusercontent.com/48590261/182026353-b808d19f-06d6-49bd-b1b7-ef167adb5361.mp4

**Comment by esm7** [comment]
To understand the source of the issue, can you try the following:
1. After you choose a file and the query in Map View updated, clear it, then focus on the new file's pane (e.g. 'Blabla') again. Does the map update back and then changes the zoom & pan properly?
2. Does it work any differently if you switch files using the quick switcher (Ctrl+O by default I think) instead of the file explorer?

Also, is there possibly some error showing up in the Obsidian Developer Console?

**Comment by Darkbluetest** [comment]
1. No, doing that at the end the map, shows only the Blabla location but do not centers neither zoom around it. It simply filters out all locations except the Blabla. 
2. No, any difference. It is exactly the same.

The console does not give any error when selecting the notes, except for the note "Turbine" 8which BTW is the only one that the zoom and center works):
![image](https://user-images.githubusercontent.com/48590261/182027519-fc6ab476-cc7e-4648-9dcf-aa526d463b3f.png)

**Comment by Darkbluetest** [comment]
Hi, there is some improvement about this? This functionality is still broken (at least for me...) with the last update.

**Comment by esm7** [comment]
Wow, it completely slipped my mind that this is still open.
I remember working on it and making substantial improvements to make this flow more robust, but it was too long ago, I don't recall how it worked out! It must be in the 2.2 version that I've been cooking for some time...
I really hope to be able to continue next week where I left off and release that version soon, after also verifying that it solves this issue.

**Comment by Darkbluetest** [comment]
I have just tested 2.2.0, there is no changem I mean, it still does nto work, and it behaves just as described in this topic. Just to tell my feedback.

**Comment by Darkbluetest** [comment]
Hi, I wanted just to know if you have tried to fix it in the v2.2.0 but failed (as it seems to me...) or if it may be fixed in the next release.
Thanks!

**Comment by esm7** [comment]
I was unable to locate the code that was meant to fix this, it was somewhere in July :-/ But I know what I did and will recreate it. Sorry for the holdup, I know how much this is troubling you (and likely others too).

**Comment by Darkbluetest** [comment]
Hi, I wanted just to know if you could work on this, or if you are going to release a new version soon. If it could be fixed, I could advance. Anyway I wanted also to thank you for your work in this plugin.

**Comment by Darkbluetest** [comment]
Just in case it helps, it works if there are 2 or more locations in the selected note, when the note has only one location, it does not follow the note...

**Comment by Darkbluetest** [comment]
I suspect that when a note is selected in the tree, you run the "Fit" function (the same that is ran when user clicks "Fit" button), because the "Fit" button behaves just the same, if the selected note has " or more locations, then it centers and zoom around the locations, but if the note has only one location, it does nothing (even if the note is off-screen)

**Comment by esm7** [comment]
It's in my shortlist of the most important next things to do in Map View, but so far this year I have terribly little "off day-job" development time, and so many things to do in this slot, it just takes me a long time to everything :(

**Comment by Darkbluetest** [comment]
Thanks. I understand the situation...let's hope you can find some more free time soon. I hope the hints I gave above will help you maybe to faster pinpoint the problem.

**Comment by esm7** [comment]
@Darkbluetest can you please test the attached fix? I believe it completely fixes the issue, which you nailed perfectly with the insight that it happens when a note has just one location!
You basically need to extract this zip to VAULT_FOLDER/.obsidian/plugins/obsidian-map-view, overwriting the 3 older files. (It won't hurt to back up this directory first.)
[map-view.zip](https://github.com/esm7/obsidian-map-view/files/10313210/map-view.zip)

**Comment by Darkbluetest** [comment]
Hi, thanks for this. Yes, it works correctly! (it still opens the note always in a fixed/same pane, but I think you fixed that in the yet-to-release 2.3.0, if I am not wrong).

When centering on the selected note it jumps to it -except if it is close to the current location-, I don't know if it could be done (added an option...) to move/scroll to the selected's note position instead. It is just a detail. 

Now the follow note finally works correctly and that is super fine!

Thank you!

**Comment by esm7** [comment]
I may have missed something, because this *is* the work-in-progress 2.3.0, so the bug you're referring to was supposed to be fixed. Can you elaborate what flow you're seeing that doesn't work like you expect? (a video is always the best if you can!)

**Comment by Darkbluetest** [comment]
Hi
Here a capture in video, with two open panes, each one with a note with location/s. It shows that the note clicked in the map opens always in the first (left most pane), regardless to have the second one selected. Then I shwo what happens if the first pane is closed: the map can't open a note at all when the user clicks on the map icon of some location.

https://user-images.githubusercontent.com/48590261/209825652-e2dc54a7-02e6-40a4-9061-edea6177a388.mp4

**Comment by Darkbluetest** [comment]
I see, well the "multiple different options" for each type of click sounds interesting. I wonder which type of options are you considering and if they could solve the problem.

Althoug it seems to me that a smooth and transparent (no special action from user required) way of operating is the ideal, so if making the plugin keep track of selection change is possible, maybe it should be considered even if it does not seem to be the official way of Obsidian, or at least give an option. But I don't the possible consequences neither if these news different options you are considering could be a transparent solution...

**Comment by esm7** [comment]
Just released the fix in 3.0.0, so I'm closing this issue. I'd love to follow-up on your idea for a new pane opening logic, and it would help me not forget it if you open a separate issue for it :pray:
