### ISSUE TITLE
[feature request] add links between pins in the map view

### ISSUE THREAD

**Issue by Xieleilab** [esm7/obsidian-map-view#116]
in obsidian, the links between notes are the important features, so in the mapview, if two notes are linked, the corresponding pins of thses nodes can also be linked by adding a line btween them, just like the OD (origin-destination)graph in the QGIS sofeware, in these cases, the links between nodes can be clearly witnessed in the map! this function is suggested to be added and set to be able to show or hide

**Comment by dev0x42** [comment]
+1 to above request! Love the current map view, but having links between notes in the map view would be amazing! When I'm planning vacations, it would be really cool to visually see daily routes as lines between notes on the map :)

**Comment by esm7** [comment]
Added as part of the just-released 5.0.0.
