### ISSUE TITLE
FR: Define and Show Persistent Labels on a Map

### ISSUE THREAD

**Issue by monomolecular** [esm7/obsidian-map-view#117]
Here's my use case: I made a map of all my neighbors (most of which I only see once a year at the block party) so I can remember who they are and where they live. I'd like to be able to define a label with their name (e.g. "June & Joe Smith", "Sara & Sally Saunders") so I can zoom in on my block and see who lives where without having to mouse over each marker. Same would apply for all my favorite restaurants I've got in another note. 

I should point out that I have all of them in one note. I'd be ok making them all individual notes and being able to show the note name as the persistent label if I had to. Or both options would be twice as nice. :)

Love this plugin. Thank you! I'm using the heck out of it!

**Comment by esm7** [comment]
That's a really nice idea, I'll look into it. Thank you!

**Comment by mayurankv** [comment]
Would also love this :)

**Comment by esm7** [comment]
I'm happy to update that the just-released v5.0.0 adds this feature.
