### ISSUE TITLE
No Markers are added to the map

### ISSUE THREAD

**Issue by ohare93** [esm7/obsidian-map-view#12]
I have created multiple notes using the right click menu while in the map. I have made inline locations, and front matter locations, and they both look fine in the note itself. I have created these notes in sub folders, and in the main folder of my Vault. I have added location data to new notes, and make new notes for testing purposes. I have opened and closed the map view, restarted Obsidian, and disabled then reenabled the plugin.

Yet I have never once seen any Marker on the map :sweat:

**Comment by esm7** [comment]
That's strange, can you post a note or two (maybe one full note with an inline location and one full note with a front matter location) so I can try and understand what's wrong?

**Comment by ohare93** [comment]
The following note content does not show up, even if I remove either of the references:

```
---
location: [55.67962302113141,-347.4226927757264]
tags: Locations
---

Game


`location: [55.67962907026126,-347.4227115511895]`

```

**Comment by ohare93** [comment]
Perhaps it is worth noting that I am on Linux (specifically Kubuntu 20.04), though it does not work on my Windows machine, or my iPhone.

**Comment by esm7** [comment]
Where are these numbers from? Lat is supposed to be between -90 to 90 and lng between -180 and 180.

**Comment by ohare93** [comment]
I got them from inside the Map view in Obsidian, with the right click copy menu.

**Comment by ohare93** [comment]
Aha! I was one world to the left! :sweat_smile: When the map opened with the world, I must have scrolled around to see the boundaries, and ended up circumnavigating the globe once to the west. I then set my hometown as my default, which kept me over there each me. I did not assume that would produce different results :sweat_smile: :laughing: 

I can now see the markers! By being in the correct globe, and not in the minuses. But perhaps this is a bug that minus coordinates can happen? :sweat_smile:

**Comment by esm7** [comment]
Wow, indeed the "copies" of the world when the map is zoomed all the way out lead to "wrong" coordinates! I'll see what I can do to prevent this from happening, thanks for finding this!

**Comment by ohare93** [comment]
> Wow, indeed the "copies" of the world when the map is zoomed all the way out lead to "wrong" coordinates! I'll see what I can do to prevent this from happening, thanks for finding this!

Haha no problem, mate. I am especially talented at breaking software, and will celebrate this small victory that it is not my own for once :smirk: 

You should be able to just loop around the horizontal coordinates (including when one sets their default view) with something like ` ( (x + 180) % 360 ) -180`

**Comment by esm7** [comment]
Turns out that Leaflet has a very cool setting `worldCopyJump` that very smoothly "jumps" to the "central" world, seems like the perfect solution here :sunglasses: 
Will be fixed in the next version.
