### ISSUE TITLE
BUG: queries don't work when the file's title contains a comma (",")

### ISSUE THREAD

**Issue by cocofoco** [esm7/obsidian-map-view#125]
## Problem
As per title, I noticed that when I tried to query files that contained a comma in their name, the query didn't work.

[Here is a gif that shows the problem](https://i.imgur.com/Vlu1yYK.gif)

## what I've tried
1. Moving the file with "," in the title from subdirectories to root folder → didn't work
2. Using "linkedfrom:" query and "linkento:" query → both didn't work
3. linking to notes that contained different types of locations (inline geolocation, front matter...) → didn't work

## current solution

I couldn't find any other workaround. 
The only way is to rename the file to be used in the query.

### comment

I'm wondering if it's a problem that can be easily solved or not, as I really like this plugin, but all my daily notes have the format "YYYY.MM.DD - dddd**,** Do MMM", therefore I wouldn't be able to use it to its full potential.

**Comment by esm7** [comment]
Fixed in 2.3.0 (not released yet).
