### ISSUE TITLE
zoom to my current location

### ISSUE THREAD

**Issue by wybert** [esm7/obsidian-map-view#126]
Add a button to zoom into the device's current location

**Comment by esm7** [comment]
I wish this would have been more straight-forward, but the Obsidian developers don't agree to add location permissions to the app (for security considerations), so no plugins can query the device GPS.
However, a few weeks ago I found a work-around that seems to work really well and will soon work on integrating it seamlessly into the plugin.

**Comment by esm7** [comment]
Didn't update here, but for many use cases this actually works in Map View for a while now, see here: https://github.com/esm7/obsidian-map-view?tab=readme-ov-file#gps-location-support
