### ISSUE TITLE
Bug: "Show on map" opens map in the sidebar overriding the file explorer tab

### ISSUE THREAD

**Issue by A-Costa** [esm7/obsidian-map-view#127]
First of all, great plug-in and thank you for your work!

When right-clicking on a note in the file explorer and chosing the `Show on map` option, if the map view is not yet opened in any tab, the map will be opened in the sidebar overriding the file explorer. 

I've made a screen-video to show what i mean:

https://user-images.githubusercontent.com/17851789/200420822-6531154d-98d9-46de-8a6e-b8e7216a9b8b.mp4

In the desktop version of Obsidian this is just an annoyance cause it forces to re-open the file explorer with the command palette, but on iOS this becomes extremely painful. I've reproduced it on my iPhone and i haven't yet found a way to remove the map tab from the sidebar.

It would be nice if the behaviour would be to always open the map view as a new regular tab.

**Comment by esm7** [comment]
Fixed in 2.3.0 (not released yet).
