### ISSUE TITLE
Embed windowed mode in obsidian note?

### ISSUE THREAD

**Issue by wang1943** [esm7/obsidian-map-view#130]
Hello, great plug in! A feature request (or help if it's not already implemented?) here. I'm wondering if you are considering make a windowed mode instead of full tab as of current. I can imagine a lot more use cases for where the bulk of notes contains a lot of content and several windowed interactive map embedded across several locations in the note.

**Comment by esm7** [comment]
See https://github.com/esm7/obsidian-map-view/issues/118.
I'm aiming to complete this in my next round of improvements to Map View.
