### ISSUE TITLE
Bug depending on Base color schema

### ISSUE THREAD

**Issue by Darkbluetest** [esm7/obsidian-map-view#136]
Hi

I have just found a bug, but I don't know if it comes from Obsidian itself or the plugin. If in Obsidian setting, the Base color schema is set to "Dark", the map is seen like that:
![Snag_e7aea46](https://user-images.githubusercontent.com/48590261/215267024-2e5d843f-cdea-45a5-acfc-e543aaa7948c.png)
But if it is set to "Adapt to system" (and the system is in dark mode), then the map is:
![Snag_e7c2f0b](https://user-images.githubusercontent.com/48590261/215267084-23294d3b-27ed-4796-91a1-c13ef3723891.png)

Maybe could it be checked so it is so like when "Dark" is selected? Or at least give an option (if you prefer)?

Tx

**Comment by t3mujin** [comment]
Same thing happens to me, when I have my Base color scheme settings set to "Adapt to System" the view in all maps defaults to Light.
