### ISSUE TITLE
every time i open map view it get zoomed out to the world, not the actual point?

### ISSUE THREAD

**Issue by zeltak** [esm7/obsidian-map-view#14]
Hi!

first of all thx so much for this amazing plugin! i love it

i have multiple MD files i have now added LAT/LONG:

```
tags: [ nyc]
priority: Done
rating: 3
location: [ 40.713012695312,-74.007125854492]
```

yet every time i open map view when in a current note i only get the entire globe:

![image](https://user-images.githubusercontent.com/498410/126868043-c73e0161-8d56-4719-aaa9-86cab0562eed.png)

Am i not supposed to see the actual LAT/LONG of the current note im viewing or am i getting this wrong?

thx a lot!

Z

**Comment by esm7** [comment]
When you're in a note you can jump to its corresponding map location using "show on map" from the menu.
If you just open the map view, it shows the view defined as the default (which you can save using the "set as default" button).
Hope this answers what you meant.

**Comment by zeltak** [comment]
thx so much!

yes this also just opens the large scale map..is that a bug?


![image](https://user-images.githubusercontent.com/498410/126873594-8b105a15-2457-40b6-ace6-d919e780aa99.png)

**Comment by esm7** [comment]
Can you elaborate more on what you're doing?
e.g. how does the problem-causing note look like, what are you clicking etc?

**Comment by zeltak** [comment]
sure and thx again for the quick reply

here is the note header:

![image](https://user-images.githubusercontent.com/498410/126874038-d648a00c-7cf5-49e3-96a1-a8644be24b77.png)


i then click as you said in the menu `show on map`:

![image](https://user-images.githubusercontent.com/498410/126874067-cccf668f-9419-43ff-a738-a8c6e3e30fa3.png)


but only get the entire world map

![image](https://user-images.githubusercontent.com/498410/126874089-99187de3-42fd-484c-942b-bf6e7576c050.png)


happy to further debug, thx so much for this awesome plugin!

Z

**Comment by esm7** [comment]
Many more questions, because that's not supposed to happen!
1. What version of the plugin are you using?
2. Can you show the note as markdown text?
3. What plugin/theme are you using to render the preview like that? Maybe it's overriding something Map View is doing? :thinking:
4. Is it behaving the same if you're clicking Show on Map from markdown edit mode? How about right-clicking the location in markdown edit and clicking "Show on Map" from that context menu?
5. Can you attach your plugin configuration file `$VAULT/.obsidian/plugins/obsidian-map-view/data.json`?

**Comment by zeltak** [comment]
Hi sure

> What version of the plugin are you using?
0.07

>Can you show the note as markdown text?

```
---
tags: [ nyc]
priority: Done
rating: 4
location: [ 40.784240722656,-73.948348999023]
---


# Ivan ramen

Fantastic pickled dikon with XO sauce and great all around ramen place  
```

> What plugin/theme are you using to render the preview like that? Maybe it's overriding something Map View is doing? 🤔

the base theme that came with obsidian 

> Is it behaving the same if you're clicking Show on Map from markdown edit mode? How about right-clicking the location in markdown edit and clicking "Show on Map" from that context menu?

rechecked and same behaviour 

> Can you attach your plugin configuration file $VAULT/.obsidian/plugins/obsidian-map-view/data.json?

sure attached 
[data.json.zip](https://github.com/esm7/obsidian-map-view/files/6872796/data.json.zip)

**Comment by esm7** [comment]
Thanks to your config file I was able to find & fix the issue, thank you!

**Comment by zeltak** [comment]
thx for the fix!

unfortunately it seems now on my system pressing the map view freezes obsidian :)

as always happy to help debug!

best

Z
