### ISSUE TITLE
Embedded Map - Dynamic Filter

### ISSUE THREAD

**Issue by cjt3** [esm7/obsidian-map-view#140]
I love the ability to embed maps directly in notes and am using this extensively for trip planning.  When I do this, the mapview command includes:

     `"query":"linkedfrom:\"(note path)"`

Is it possible (or if not could it be possible) to make this a dynamic link to the current note (whatever the path might be).  That would allow the mapview code to be included in a template so the embedded map automatically generates for new notes.

As an example, in Dataview you can query items that link to a specific note by using:

     `FROM [[(note path]]`

but you can also query items that link to the current note (whatever the path) by using:

     `FROM [[]]`

**Comment by esm7** [comment]
I'm really happy you asked, because while planning the embedded map functionality I was wondering whether this kind of feature would prove useful or not, and I wasn't sure so I put it aside.
Part of what I was answering myself is that this can largely be achieved with template plugins (like the daily note or templater).
What do you think are the added benefits of including the template mechanism built-in?

**Comment by cjt3** [comment]
I had not thought about using Templater to accomplish what I was looking for. 🤦‍♂️ Thanks for the suggestion - I will definitely do that!

That solves my main issue, but there could still be a couple benefits of having a dynamic link to the current page.  One would be that you could copy the mapview command from one file to another and have the map automatically generated.  Another would be that the map would automatically update any time you change the name or location of the note.  However, now that you've pointed out using Templater I could easily use that (and maybe also Quick Add).  It wouldn't be automatic, but it's quicker than making the changes manually as I have been.

**Comment by esm7** [comment]
The way it seems to me right now, the cases you described, although very real, are possibly too niche to justify a separate templating mechanism, and I rather focus the Map View development time on things that aren't covered by other plugins. Please update if you see more cases or think otherwise!
