### ISSUE TITLE
[BUG?]seems to never focus on the correct note location

### ISSUE THREAD

**Issue by zeltak** [esm7/obsidian-map-view#141]
Hi again 

Coming back to map-view after a while

I still dont seem to get it  (and im a GIS professor ;-))

see video: https://paste.xinu.at/gmQ3S/

if I have this in the FM yaml:

```
---
tags:
- review
- באר-שבע
status: 5
rating: 3
location: [ 31.371154785156, 34.823097229004 ]
counter: null
---
# .דלפק

חנות שתמחה בפיתות שף
```

and I issue map view `open map view` am i not supposed to get a zoomed view of the actual note location , ie `31.371154785156, 34.823097229004 `. currently it only opens in every not the same world view

![CleanShot 2023-02-19 at 13 26 04](https://user-images.githubusercontent.com/498410/219944977-189e9f58-8532-4362-ab3b-077feb6c178f.png)

what am I missing here :)

**Comment by esm7** [comment]
Welcome back! ונחמד לראות עברית כאן :)
AFAIK all the old bugs of not opening at the right state are long gone. I'd love to help but I just need to know a few details:
1. Is this the latest Map View version?
2. How are you opening Map View? Is it from the note's menu? The global ribbon icon? Something else?

**Comment by esm7** [comment]
It might be the "focus in map view" menu item that you're looking for (from the note's context menu), rather than the global command of opening Map View with the default state.

**Comment by esm7** [comment]
Oh sorry I just noticed you also pasted a video.
Try to right-click the 'location' line and click "show on map", or alternatively open the note context menu (the 3 dots on the far right), where you should see "focus <note name> in Map View". That should do what you're aiming for.

**Comment by zeltak** [comment]
אהלן :)
thanks for much for your kind and swift response!

 I see now yeah thats much more of what I had in mind

it seems though that it still is opened pretty zoomed out for example for a location in NYC it opens like this

![CleanShot 2023-02-19 at 14 51 43](https://user-images.githubusercontent.com/498410/219949104-2b9af03d-ac17-4c54-a136-60192323f98f.png)


as opposed to when I manually zoom in into the actual location (ie Katz deli:)

![CleanShot 2023-02-19 at 14 52 40](https://user-images.githubusercontent.com/498410/219949153-09c02c99-c8ff-4274-8ca9-fe0fd70fb97e.png)


is that by design? 

thanks so much again for you epic work on this , its very much appreciated

תודה רבה :)

**Comment by esm7** [comment]
Can you play around with your "default zoom for 'show on map' action" in the setting? It's possible that the default doesn't look so great on your desktop.

**Comment by zeltak** [comment]
yup that did it 😊
thanks so much!

שיהיה שבוע נפלא
