### ISSUE TITLE
FR: Support routes

### ISSUE THREAD

**Issue by nununo** [esm7/obsidian-map-view#142]
The plugin currently supports single points.
It would be great to be able to draw routes based on a list of coordinates.

Maybe it could be optionally disabled.

If a note had a list of coordinates, that list would be rendered as a route.

Suggested implementation:

**Option 1: `route` key in frontmatter with list of locations**

This approach is limited to one route per note.

```yaml
---
route:
  - [40.6892494, -74.0466891]
  - [40.6892123, -74.0466123]
  - [40.6892456, -74.0466465]
  - [40.6892789, -74.0466789]
---
```

**Option 2: `route`key in frontmatter with inline locations**

Similar to how `locations` currently works. All locations in the note would be harvested and treated as a single route.

This approach too is limited to one route per note.

**Option 3: `routes` in frontmatter with list of `route` with list of locations**

```yaml
---
routes:
  -
    - [40.6892494, -74.0466891]
    - [40.6892123, -74.0466123]
    - [40.6892456, -74.0466465]
    - [40.6892789, -74.0466789]
  - 
    - [40.6892494, -74.0466891]
    - [40.6892123, -74.0466123]
    - [40.6892456, -74.0466465]
    - [40.6892789, -74.0466789]
---
```

I wonder... the YAML in this one is somewhat weird and confusing.

Thanks!

**Comment by esm7** [comment]
It's somewhere in my roadmap to add GeoJSON and GPX support (see https://github.com/esm7/obsidian-map-view/issues/50), I believe this would satisfy the same need in a more standard fashion?

**Comment by nununo** [comment]
Ah perfect. That's definitely better. I'll close this one then. Thanks!
