### ISSUE TITLE
Change height of embed

### ISSUE THREAD

**Issue by ltroj** [esm7/obsidian-map-view#147]
Is there a way to set the height of an embedded map? Currently my embedded view is very wide but short.

Documentation says
> You can make light adjustments to the view from within the embed (change its zoom, pan or height), and if you want these to be saved, click the 'Save' button that will appear.

But I can't find information on how to set the height parameter.
``"height": 800,`` didn't work for me.

Is it possible?

**Comment by esm7** [comment]
The easiest way to go would be to use the GUI: in the map embed in the View drop down, below the "update from open Map View" there is a box with the height. If you change it and click Save, it should change the height.
If for some reason you want to set it manually in the code block, the name of the parameter is embeddedHeight. (You should see it added/updated if you change the height from the box in the UI.)
