### ISSUE TITLE
Custom labels for inline geo links

### ISSUE THREAD

**Issue by devinbaillie** [esm7/obsidian-map-view#149]
If I have a note with multiple geolocations, is there any way to give them labels other than the note name?

Maybe I'm missing something simple, but if I put:

`[](geo:78.33720203451263,-44.6484375)`

I get a pin on the map view in the middle of Greenland, but it's labelled with the note title.  Is there any way to give this location a custom label, such as "Middle of Greenland"?

**Comment by esm7** [comment]
Yes, you can give the link itself a name, e.g.
`[Middle of Greenland](geo:78.33720203451263,-44.6484375)`

**Comment by devinbaillie** [comment]
Thanks for the response.  That's how I figured it would work, but it's still labelled with the note title.  See the attached screenshot.  I guess this should be filed as a bug report then.
![image](https://user-images.githubusercontent.com/38236959/227733825-c0f159cb-daef-4c00-ac1c-14f4e1f10111.png)

**Comment by esm7** [comment]
I see how that I made this functionality work only on mobile, under the assumption that on desktop most people would use "show note preview on map marker hover", which shows much more context than the link name.
How about turning on this setting and seeing if it helps you?
If after that you will still think that the popup should include the link name, I will bring it back as a setting.

**Comment by devinbaillie** [comment]
Thanks, I had that setting enabled, but didn't have the page preview core plugin enabled, so all I got was the title.  I can make this would work, but the link name instead of the title would be preferable.

If I use just the note preview, it doesn't show the note name, and if I use both note name and note preview, it makes two separate popup.  If there's a way to have the note name show up at the top of the note preview, it would be better, though I'm not sure how easy it would be to add the title to the top of the preview?  I think I can make it work as is, I just need to make sure my links have the correct context near them in the note so it displays with the page preview, but it would be easier if I had the option of using the link name instead of (or in addition to) the note name.

I'm making a map of my acreage and all the plant varieties I've got.  I have several different varieties of apple trees, for one example.  I originally figured that I would have one note named Apple Trees, with a link named for each variety so they show up correctly.

If I use the note name popup, then I need to move each of the links to their own note. Then I can link to them from the Apple Trees note.

If I use the note preview popup then for plants that only have one variety, the note title isn't included, so I have to put the plant into a header or something so it shows up in the popup.

I'm not sure which approach I will take yet, I need to see how I'm using the map going forward, whether I prefer the cleaner look of the small title popup or more context from the page preview popup.  I suppose ideally, to make it as customisable as possible, I'd want the option of having the preview popup with a title that is an optional combination of note name, link name, both, or neither (if that makes sense?).  Maybe even a way to set this in the embedded map options as opposed to a global setting (or to override the global settings?).  That way I could use one popup setting for my acreage map, and a different one if I were planning a road trip or something.

I hope all this makes sense, and I don't come across as ungrateful.  I appreciate all the work that goes into making this extension (seriously, thank you, I've been looking for a solution for mapping out my acreage for a while before I discovered this), and I can make it work as-is if you don't have time to add features just for my specific use case.

**Comment by esm7** [comment]
Unfortunately the note preview is completely controlled by Obsidian, all Map View can do is mark the highlighted line, and I was unable to find a way to control it further (i.e. to display the note title).
But customizing Map View's own note popup (the one that currently shows just the title) is very doable, it actually used to be this way before I made the note preview. I'll bring it back.

**Comment by devinbaillie** [comment]
That sounds great, thanks so much!

**Comment by aubreyz** [comment]
I'd definitely +1 this. Great plugin btw (sent some coffee). For inline stuff it isn't that useful for every marker just to show the note name - impossible to work out what each marker is (and the note preview hover shows nothing else no matter the setting). Should show both note name and the individual link name - maybe with a slightly smaller font, or over two lines (note//name)

**Comment by aubreyz** [comment]
PS: Even if I do enable the Page Preview Core Plugin (which I don't want to do) it doesn't really help to identify what the pin is - I just see a whole collection of geo links on the area of the relevant page. So definitely bring back the individual link name in the popup...

**Comment by martinjo** [comment]
I just ran into this issue now. Some kind of customization would be really nice!

**Comment by esm7** [comment]
In the upcoming days I'm planning to work a few hours on Map View and this will be included.

**Comment by esm7** [comment]
Added in 3.0.2.

**Comment by aubreyz** [comment]
This sounds awesome @esm7 - I just updated the plugin but
URIs of the form
[Piggle Road](geo:54.3541342,-2.5487756)

on hover are still showing up all just with the containing file name, not the location
Unless there is a setting I missed

**Comment by devinbaillie** [comment]
Perfect, thanks for changing it.

**Comment by esm7** [comment]
@aubreyz there is a new setting under "Marker Hover & Previews": "show inline link name on marker hover".
You should set it to "always".
Let me know if it works as expected.

**Comment by devinbaillie** [comment]
> @aubreyz there is a new setting under "Marker Hover & Previews": "show inline link name on marker hover". You should set it to "always". Let me know if it works as expected.

Works as expected for me, thanks.

**Comment by aubreyz** [comment]
Ahh yes, with the setting on that's great. 

Issue is the coloring of the popup. Obviously to do with my theme (which is just default albeit with some snippets)
The color of the File name and the link differ with the latter being nearly invisible. I'll need to work on what CSS is styling them but that's going to be a potential problem for some people. 

![image](https://github.com/esm7/obsidian-map-view/assets/25100168/41537850-6fc2-4984-9382-72ac6f27da3b)

**Comment by aubreyz** [comment]
Yes that solves it completely - and useful to be able to size them. Would be useful to have a complete snippet of various stuff useful for maps.
