### ISSUE TITLE
More Zoom

### ISSUE THREAD

**Issue by devinbaillie** [esm7/obsidian-map-view#150]
Is there any way to increase the maximum zoom level?

I realise that I won't get any more detail out of the tiles or anything, but it would be helpful to be able to magnify further when there are markers close together to be able to zoom in more to distinguish them.

I'm aiming to make a map of my acreage, with the locations of the specific varieties of trees/shrubs/plants that I've planted over the years, connected to my notes with care instructions, planting/pruning/care history, etc.  But I have some bushes spaced 3' apart, and it's just about impossible to distinguish them at the maximum zoom level.

**Comment by esm7** [comment]
Yes. In the Map View settings see the toggle "allow zooming beyond the defined maximum".
You can also experiment with increasing the max zoom of the map source you are using. Scroll down the settings pane to Map Sources, locate the map source you're using (e.g. the default CartoDB), then increase the rightmost number (by default 19). If after reloading Map View the map stops working at a high zoom, bring the number back to the highest you got working, and "allow zooming beyond the defined maximum" will take you further.

**Comment by devinbaillie** [comment]
Great, this is perfect.  Thanks!
