### ISSUE TITLE
Inline geolocation link AND link to a note

### ISSUE THREAD

**Issue by SiliasGH** [esm7/obsidian-map-view#157]
Hi,
I love this plugin! Thank you for creating it. :)

Planning trips with two panes open and the "follow active note" option on is awesome! In the first pane, I write down my plan for the trip and insert all the geo-links I'm interested in. In the other pane, these geo-links appear on the map - it's awesome! :)

BUT:
Very often, I feel the urge to create a note out of one of these geo-links and would like to have everything linked together. So here is my question:
Would it be possible to have the geo-link simultaneously be a note-link? Currently, when I click on a geo-link in my note, I am asked how to open that link, as shown below:
![image](https://user-images.githubusercontent.com/51036225/233804418-69e363ee-e6be-42d2-896a-4c27245a9ef7.png)

Instead of that, I would like Obsidian to open a note with that filename. :)

Kind regards,
Sebastian

**Comment by SiliasGH** [comment]
... alternatively, the following would be a very nice feature:

It would be very nice, if not only the geo-links of the active note would appear in the map view, but also all the geo-links of notes, that link to the active note :)

... => that would mean for my planing workflow:
I would have 2 options for inserting geo-links to my trip-planing-note:
1) directly, as an inline geo-link, how it is already possible
2) indirectly, as a new normal note, that links to my trip-planing-note. In that note I could use all possibilies to insert geo-information, e.g. inline or in the frontmatter. 
BUT: => these geo-information, would appear in the mapview of the first note

? 

It that would be possible, you'd deserve more than just one coffee! :)

**Comment by SiliasGH** [comment]
wowwww, sorry for the confusion - I just discovered filters, which accounts exactly for that issue!!! :)
I just have to use the expressions "linkedfrom", this is just.... awwwesome!!!! :)

**Comment by esm7** [comment]
Except that, you also mentioned https://github.com/esm7/obsidian-map-view/issues/144, which many people (including me) really want.
