### ISSUE TITLE
Combined Query does not work

### ISSUE THREAD

**Issue by SiliasGH** [esm7/obsidian-map-view#158]
Hi,

you wrote in your doc:
Use linkedfrom:"$PATH$" OR linkedto:"$PATH$" to include markers that the active note links to and also markers that link to this file.

But if I specify that term in my settings, just the first $PATH$ ist evaluated, the second is not evaluated and therefore an error occurs

**Comment by esm7** [comment]
What an annoying bug! I'll take care of that as soon as I get a few hours to work on the next bug-fix version.
