### ISSUE TITLE
Nested tag support for querying

### ISSUE THREAD

**Issue by treardon17** [esm7/obsidian-map-view#159]
Hi there! First off thanks for such an awesome plugin 💥 

I'm trying to come up with a good workflow for tracking my travels. Currently I have a folder named "Activities" where I put all of my travel notes. Each activity note has a nested tag (ie. `activity/food`, `activity/hike`) but none of the activity notes have the top level `activity` tag on them. I also have a folder named "Places" where I put all of the places I want to go or am interested in. I would like to have a map of all the places I've had an activity, and a different map describing all of the places I want to go.

Based on how the dataview queries work, I expected a configuration like this to show all notes tagged with `activity` (including nested tags):
```mapview
{"name":"Default","mapZoom":1,"centerLat":41.244517994223585,"centerLng":-37.26562500000001,"query":"tag:#activity","chosenMapSource":0}
```

Unfortunately, this only queries for notes that have exactly `activity` as a tag. I ran across this issue https://github.com/esm7/obsidian-map-view/issues/10 and was hoping since other people are using nested tags this would be a nice feature to complement nested tag support for icons.

**Comment by esm7** [comment]
You're right, tag wildcards work for icons but not for queries, and that's an annoying gap that I want to close soon. Will fix.

**Comment by esm7** [comment]
Added in 3.0.2.
