### ISSUE TITLE
By me a coffee

### ISSUE THREAD

**Issue by aubreyz** [esm7/obsidian-map-view#160]
As  matter of interest I paid for a very small cup of coffee via your link on the 24th. 

I go this E-mail confirmation

Thank you.
You've made a purchase from Google Commerce Limited on Google Play.
Order number: GPA.3345-0300-6438-75486
Order date: 24-Apr-2018 14:01:44 BST

However an hour later I see I got another email without any explanation as follows

Your purchase from [MyCafeCup.com](http://mycafecup.com/) on Google Play has been cancelled. Any charges made will be refunded.
Order number: GPA.3345-0300-6438-75486
Order date: 24-Apr-2018 14:01:44 BST

Nothing wrong with credit cards etc etc... Clearly they want you caffeine free. 

However I still show up on your coffee supporters page -- did you get the coffee??

**Comment by esm7** [comment]
I don't know why it shows your purchase as cancelled - I did get it! Thank you for the support! :pray:
