### ISSUE TITLE
Allow tag that denotes inline locations to include nested tags

### ISSUE THREAD

**Issue by mjknght** [esm7/obsidian-map-view#164]
It would be great if the tag that denotes inline locations permitted there to be nested tags. For example, if the tag is `#locations` then `#locations/cities` and `#locations/buildings` would both be permitted. At present, if there's anything after the tag at all, it is not recognised. Thanks for your consideration!

Original comment below:

> This works very well indeed – thank you so much for this! Just updated, and very grateful for how easy this makes the plugin to work with.

> This is great already, but I do have one small request, which is for the tag to allow for nested tags. Let me explain why. I have lots of `#locations` tags already in my notes, but they all have nested tags, e.g. `#locations/cities` `#locations/buildings` etc. At the moment I need to add this tag for a second time without any nested tags for the location to be picked up. But if all that was required was for the top-level tag to be present, suddenly everything I already have would appear on the map. Thanks for you consideration and thanks again for adding this feature!

_Originally posted by @mjknght in https://github.com/esm7/obsidian-map-view/issues/135#issuecomment-1547367139_

**Comment by esm7** [comment]
For clarification: how I plan this would work is that the "tag that denotes inline locations" would be able to accept a wildcard (as in other places in Map View), so you could write `#locations*` in the settings.

**Comment by esm7** [comment]
Added in 3.1.0.

**Comment by esm7** [comment]
(rolled back the release because I made a mistake in the process, will hopefully re-release it tomorrow)

**Comment by esm7** [comment]
(update: fixed and re-released now)
