### ISSUE TITLE
Add Custom API (Maptiler) info to documentation

### ISSUE THREAD

**Issue by bryanwhiting** [esm7/obsidian-map-view#165]
First of all, Thanks for the AMAZING app!!! Not to bash on anyones parade, but I tried figuring out the obsidian leaflet app and it was so confusing. Docs need to be updated there. But within 2 min I knew exactly how to use this and then some. Great design with the queries!

For anyone else that this is helpful for, here's some sample documentation:

If you'd like to add a provider that requires an API key (such as maptiler), get an API key and construct the proper URL. For example, the [Raster Tile Providers](https://wiki.openstreetmap.org/wiki/Raster_tile_providers) documentation says the URL is `https://api.maptiler.com/maps/outdoor/{z}/{x}/{y}.png`, but that won't work without your key. Instead, replace `ABCDEFGH` below with the key that maptiler provides you.

```
https://api.maptiler.com/maps/outdoor/{z}/{x}/{y}.png?key=ABCDEFGH
```

This opens any of the other endpoints as well, such as `/maps/basic/` and `/maps/pastel/`, etc. Even easier is that once you sign up, Maptiler provides in their [documentation](https://cloud.maptiler.com/maps/) formatted URLs with your key already. For example, see [hybrid](https://cloud.maptiler.com/maps/hybrid/), which has the following URL:

```
https://api.maptiler.com/maps/hybrid/{z}/{x}/{y}.jpg?key=ABCDEFGH
```

**Comment by esm7** [comment]
Added to the README, thank you!
