### ISSUE TITLE
"Show note preview on map marker hover" not working on mobile application

### ISSUE THREAD

**Issue by dianjinoh** [esm7/obsidian-map-view#167]
map view version: 3.1.1
mobile: iphone 8
os: 16.4.1
description: 
when clicking on any map marker in the mobile app, only the pop-up with the map name is shown and not the note preview. this is working fine in the desktop version. I have disabled every other plugin and restarted the application as well

actual:
![mobile](https://github.com/esm7/obsidian-map-view/assets/53361389/518b44a6-027e-4af8-a79a-7aa4d70bdfd5)

expected:
![desktop](https://github.com/esm7/obsidian-map-view/assets/53361389/069e9522-475a-4a9d-9528-5afeaf530f13)

P.S thank you for the awesome plugin and the amazing work !!

**Comment by esm7** [comment]
To open this preview, Map View uses an undocumented Obsidian API that sometimes breaks, then I point it out to the authors and they fix it. Seems like it now broke in one of the updates of Obsidian Mobile :(
I'll see what I can do.

**Comment by esm7** [comment]
I think and hope this was fixed long ago, but either way, I have rewritten this mechanism and no longer using the undocumented Obsidian API, so it should work consistently.
