### ISSUE TITLE
Guidance: How to make an external link which also has geo information

### ISSUE THREAD

**Issue by hlascelles** [esm7/obsidian-map-view#168]
Great plugin!

I am trying to make a link to something external, and also have geo information about it. Imagine a page called "Museums".

If go with something like this. 

```
-  [221b Baker Street](geo:51.5238,-0.1588) [museum](https://www.sherlock-holmes.co.uk/) 
```

Then everything shows up on a map as a pin with a nice title, but queries to find titles to links in my documents all come back as "museum". Also it means my "named" links across my vault are not consistent as some open locations and some websites.

I can get close with something something like:

```
-  [221b Baker Street](https://www.sherlock-holmes.co.uk/)  [geo](geo:51.5238,-0.1588)
```

This gives me a nice named link, with a link to the museum website, and everything shows up on a map as a pin. :+1: . But, the map pins are all titled "Museums" "geo".

Can I say something like "Add a geo tag, but when hovering over it (or deriving data from it), calculate and show the "previous link in the document" as the popover name?" ie, when hovering, show "221b Baker Street"?

Hope I half explained that... Thanks!

**Comment by aubreyz** [comment]
Not sure I'm following exactly. You have two completely separate links

[221b Baker Street](https://www.sherlock-holmes.co.uk/)  

[geo](geo:51.5238,-0.1588)

How about 

[221b Baker Street](https://www.sherlock-holmes.co.uk/)  [221b Baker Street](geo:51.5238,-0.1588)

**Comment by hlascelles** [comment]
Yes, I think the latter ultimately gives what I am looking for, but it is a shame to duplicate the title. I suppose I am looking for something like this, but I don't think it exists:

```
 [221b Baker Street](https://www.sherlock-holmes.co.uk/,geo:51.5238,-0.1588)
 ```

The above does not work of course, I don't think that's possible as a limitation of Markdown. I wonder if Obsidian has any other way to pack in more than one "fact" into a markdown link. If not I will go with one of the other options. Thanks for the quick response!
