### ISSUE TITLE
Filter dropdown isn't working on MacOS

### ISSUE THREAD

**Issue by mfloreen** [esm7/obsidian-map-view#169]
I'm just starting to explore Map View, but WOW, I'm loving it so far. 

I have run into a bug, and wanted to report it. When viewing the map on MacOS, the Filter dropdown is overlapped by the back/forward buttons (screenshot below). The net result is that it is impossible to select the Filter settings. It works fine on iOS. I'm also running the Minimal theme, if that makes a difference. 

![Screenshot 2023-06-05 at 9 54 18 PM](https://github.com/esm7/obsidian-map-view/assets/6507971/d21e0bbb-705a-478f-8595-e7c30b26fbef)

**Comment by SiliasGH** [comment]
Same on Windows

**Comment by esm7** [comment]
I recreated the issue locally and I can't figure out a way to provide a general fix in Map View that would work for both Minimal (which makes the navigation buttons float) and the default theme (on which they are part of the layout).
I posted a request in Minimal to support this: https://github.com/kepano/obsidian-minimal/issues/574
In the meantime, until a better fix is found, you can add the CSS snippet that moves the controls further down:

```
.map-view-graph-controls {
    top: 36px;
}
```
