### ISSUE TITLE
Connect with Strava?

### ISSUE THREAD

**Issue by bryanwhiting** [esm7/obsidian-map-view#170]
If I want to connect with Strava data, would there be an easy way to plot it? Could you show me where to go?

Thinking something like [this](https://www.youtube.com/watch?v=UjEbRp8WKn4):
![image](https://github.com/esm7/obsidian-map-view/assets/18710907/7f946b25-dc38-42e7-81db-06fefaede03a)

**Comment by esm7** [comment]
This is a popular request: https://github.com/esm7/obsidian-map-view/issues/50
I'll close this issue and keep the main one, while surely counting it as another vote.
