### ISSUE TITLE
Blank or malformed inline geo location prevents note from opening

### ISSUE THREAD

**Issue by GovSat1** [esm7/obsidian-map-view#172]
I have a template with a blank geo: field. `[](geo:)`

Trying to open this note when Map plugin is enabled results in error: "Failed to load (path to file), Cannot read properties of null (reading 'groups').

Occurs on desktop and ios. Issue also presents when the geo link is malformed, IE a space between lat and long (actually, it would be nice to support with/without space, Google copies with a space by default).

To resolve either the plugin needs to be disabled or remove the geo link outside of Obsidian.

**Comment by esm7** [comment]
Will get this fixed in the earliest time slot I manage to work on Map View.

**Comment by esm7** [comment]
Fixed in 4.0.0.
