### ISSUE TITLE
Icon tagging not working

### ISSUE THREAD

**Issue by joetech** [esm7/obsidian-map-view#177]
I'm VERY new to Obsidian and Map View.  It's possible I'm doing something wrong, but I haven't been able to figure out what that might be.

I'm using Ubuntu, Obsidian 1.3.5, Map View 3.1.1

![image](https://github.com/esm7/obsidian-map-view/assets/1650878/d3025d0c-c035-4ddc-afed-4946d421c613)

Here's the "map" link with location fuzzed a bit: geo:39.4,-87.3

This is what I see when I apply a tag.  It's not working as expected.  Below is my tag configuration:

![image](https://github.com/esm7/obsidian-map-view/assets/1650878/a015626a-b12d-460e-a67a-1d2729b72312)

I also tried with one that existed on install (trip) and the same happens.  When I click through to the map, the icon is also still just the default.  I'm building out a trip plan and would love to have everything on the map with icons to help easily identify things.

**Comment by esm7** [comment]
Hi, it's hard for me to tell from your issue what kind of location you are using, an inline one or a front matter one. However, what you may not be doing (I'm guessing here a bit) is just adding a tag to the relevant note, e.g. just add `#hotel` to the note where your location is set. Alternatively, if you are using an inline location and wish to only tag that one off a bigger note, add `tag:hotel` right after the location (Map View will try to complete you while typing).
Let me know if I understood you correctly and that's the issue.
