### ISSUE TITLE
FR: Add a Fixed Map Option to Embeds

### ISSUE THREAD

**Issue by GovSat1** [esm7/obsidian-map-view#178]
With embedded maps in particular, it would be nice to add a flag that locks the map to a fixed center (possibly where +- zoom could still work), but no scrolling unless the map is opened in the main map view.

On mobile embedded map view tends to get in the way while scrolling through a note, and in most cases a fixed map would be preferred.

**Comment by esm7** [comment]
I really like this suggestion.

**Comment by esm7** [comment]
Added in 4.0.0.

**Comment by GovSat1** [comment]
Thanks! The new flag is: `"lock":true` for anyone adding it to the code blocks manually.
