### ISSUE TITLE
the font size becomes samll in the preview window

### ISSUE THREAD

**Issue by kin30528** [esm7/obsidian-map-view#179]
Hi esm7, u make a perfect plugin i love. but i dont know wht the text in the preview window becomes smaller. It makes me hard to read. Thx.

the font size in preview window
<img width="458" alt="1" src="https://github.com/esm7/obsidian-map-view/assets/121107652/a0902db4-2ee6-4bc4-89e4-27c81c8087b3">

Actual font Size
<img width="664" alt="1 2" src="https://github.com/esm7/obsidian-map-view/assets/121107652/e5f8c961-a3ce-4adc-996a-425c6e6fa7a9">

**Comment by esm7** [comment]
Does it look the same when you use the Page Preview feature (core plugin) of Obsidian?
Map View just launches the native Obsidian note preview, so I have no control over how it looks like, except applying some global CSS that would effect everything :(

**Comment by kin30528** [comment]
> Does it look the same when you use the Page Preview feature (core plugin) of Obsidian? Map View just launches the native Obsidian note preview, so I have no control over how it looks like, except applying some global CSS that would effect everything :(

Thank you for reminding me about it, I found that the problem is caused by plugin Hover editor. Interestingly, it only affects the preview windows font-size of map view.🤣
