### ISSUE TITLE
Feature request: geo URLs

### ISSUE THREAD

**Issue by D-side** [esm7/obsidian-map-view#18]
A new notation for specifying a location inline: [`geo:` URLs (Wikipedia)](https://en.wikipedia.org/wiki/Geo_URI_scheme). They're standard (RFC 5870, yr 2010) and rather widely adopted, the linked Wikipedia article goes into more detail on that.
I'm currently adding these by hand in addition to Map View's default notation, because at the moment both have their uses, but I would certainly prefer to have only one that has the advantages of both.

The practical killer feature for `geo` links for me is that **on mobile**, when opened, they trigger **app selection**. And apps can do more than just show the point on the map, some allow doing something with that point, like calling in a ride to that location.

Syntax: `[Link text](geo:LAT,LNG)` (vs. currently supported `location: LAT,LNG`)

<details><summary>Screenshot from Android (it's in Russian, but demonstrates the idea)</summary><p>

![image](https://user-images.githubusercontent.com/2567124/127769119-b8837221-906c-4fa8-ac0a-8577e225ffd4.png)

</p></details>

**Comment by esm7** [comment]
That has been an excellent suggestion, and I have incorporated it thoroughly into the 0.1.0 version just released.
It's not only the default now, I also utilized the fact inline locations can have a name to display them better, and the cursor jumps to the link name when adding an inline location.
Thank you for pointing this out!
