### ISSUE TITLE
Custom markers for inline geo links

### ISSUE THREAD

**Issue by yett1873** [esm7/obsidian-map-view#180]
I'm wondering if different tags following inline geo links could result in different markers on the map, it'd be great if we don't have to create an independent file for every single location just for different colors and shapes!

**Comment by esm7** [comment]
Hi,
Map View has a syntax for "inline tags", that can follow inline geo links in a special syntax, so they would only apply to these geolocations and not the whole note.
See [this section](https://github.com/esm7/obsidian-map-view#understanding-map-view-parsing-location-data) where it explains about inline tags.

**Comment by yett1873** [comment]
Thank you so much, should have read through the doc. Just got to know this plugin and I'm loving it!
