### ISSUE TITLE
Navigation arrows obscured by Filters overlay

### ISSUE THREAD

**Issue by Jackrabbitron** [esm7/obsidian-map-view#182]
Using Minimal theme, I noticed that the back and forward arrows can be hidden by the Filters overlay. Might be a quirk of my setup but flagging just in case, as it was confusing how to get back to the originating note. Cheers.

![SCR-20230724-ilpg](https://github.com/esm7/obsidian-map-view/assets/33181361/fed0a100-e2d2-49db-b9e7-ab9c6b29fd1e)

**Comment by esm7** [comment]
See here: https://github.com/esm7/obsidian-map-view/issues/169
Most importantly, it would help if you help ping this issue on the Minimal repo: https://github.com/kepano/obsidian-minimal/issues/574
