### ISSUE TITLE
Bug: Maps can't load locations from notes that have emojis in the filename

### ISSUE THREAD

**Issue by phil** [esm7/obsidian-map-view#189]
`LinkedFrom` and `LinkedTo` queries don't correctly load locations if the note filename contains an emoji. 

Example:
I have a note with plans for a trip to Italy. The note is named `2023-06 🇮🇹 Italy.md`, and I want to include an inline map with all the locations for my trip. Using `"query":"linkedfrom:\"2023-06 🇮🇹 Italy.md\"` won't load any other the locations in the Italy note, or any notes linked from the Italy note. Removing the emoji from the filename, and updating the query, everything works correctly.

**Comment by esm7** [comment]
Indeed I never considered file names with emojis :smile: 
Will see what I can do.

**Comment by felixbaral** [comment]
Also having this issue. All my filders have emojis and some of the files too. Issue is with folders and files.

**Comment by esm7** [comment]
Should be fixed as part of the just-released 5.0.0.
