### ISSUE TITLE
Ability to change the yaml property name map-view looks for

### ISSUE THREAD

**Issue by joecan00** [esm7/obsidian-map-view#195]
I currently use the yaml property field "location:" for more generic place names. I would like to use the yaml property name "gps:" for map-view coordinates instead of the default "location:" name. Would love to see this option added in the future.

Thanks for such a useful plugin!!

**Comment by esm7** [comment]
That's not as simple as it probably sounds, but I'm planning to refactor how Map View uses YAML (as nowadays Obsidian offers API to modify the frontmatter which didn't exist originally), and I'll look into doing this together.

**Comment by gfordinal** [comment]
@esm7 that would be great, as other plug-ins use the official api and break both empty yaml keys (as "location:" is) and array-like yaml values (as "location [lat, lang]" is) respectively.
Neither of those is valid yaml and I wonder how it appeared in the first place. If you need support developing, please hit me up, I may find some time or buy you a coffee instead.

I love your plugin, it saved me a lot of headache. Though with the official front matter api it unfortunately is not applicable anymore.

**Comment by esm7** [comment]
I started and will get it done, it's a matter of no more than a few work hours, I just need to find these :sweat_smile: 
If all goes as planned, should have the time this week or so.

**Comment by esm7** [comment]
Added as part of the just-released 5.0.0.
