### ISSUE TITLE
Maps language selection

### ISSUE THREAD

**Issue by distkeys** [esm7/obsidian-map-view#197]
I'm planning a trip to Japan and when I use Maps view it shows the map in local language.

Is there anyway to have map and places names in English like google maps?

**Comment by esm7** [comment]
Hi,
Some map sources indeed prefer to show the map in the local language, which I often find very annoying too when visiting some countries.
See the Map Sources section in the Map View documentation: https://github.com/esm7/obsidian-map-view#map-sources
It links to a big list of possible map sources you can use, and for some it also details what language the labels are at. Don't be afraid of services that require a registration, some have an extremely extensive free tier.

**Comment by distkeys** [comment]
Great!!! Used https://www.maptilesapi.com which have English labels... Thanks it worked!!
