### ISSUE TITLE
Unable to disable Font Awesome

### ISSUE THREAD

**Issue by eb2ai** [esm7/obsidian-map-view#198]
Unfortunately, the Font Awesome integration is conflicting with another tool using Font Awesome. I think it would be good to have a simple toggle to disable loading the FA scripts/css.

**Comment by esm7** [comment]
Map View can't currently work without Font Awesome (it would not be able to render map markers at all). Can you elaborate on the conflict? What tool and what is the nature of the conflict? There may be other ways to mitigate it, e.g. make sure Map View and that tool are using the same version of FA.

**Comment by eb2ai** [comment]
I'm using FontAwesome as a snippet using fonts and not the SVG version of the icons. It's an important part of my documentation and writing.

**Comment by eb2ai** [comment]
It's a valid option to disable marks entirely.

**Comment by eb2ai** [comment]
Sorry, the more I think about this... I think the best solution is to allow svg images to be used as markers. This makes it wide open for folks.

I keep responding because your tool is one of the tools I most wish to use in Obsididan. However, my outside use of FontAwesome is very fundamental. I just wish I could have my cake and eat it too.

**Comment by esm7** [comment]
I would really want you to be able to use Map View as part of your setup, but if I understand correctly, what you are asking requires a major overhaul of how Map View uses Leaflet and the Leaflet.ExtraMarkers plugin, which depends on Font Awesome and also hacks it a bit for performance reasons. If you're a developer and willing to dive into the code, it can help if you do the legwork to understand how it is achievable.

**Comment by eb2ai** [comment]
So... I just wanted to say that I love this plugin so much I changed the way I use icons so I wouldn't have a compatibility issue with it. Thanks for the great tool.

**Comment by eb2ai** [comment]
Thanks.

**Comment by esm7** [comment]
Thank you for the update, that's great to hear!
