### ISSUE TITLE
Support linkedfrom links using properties

### ISSUE THREAD

**Issue by GovSat1** [esm7/obsidian-map-view#199]
When using backlinks in the new properties fields aka yaml array, Map view does not recognize these for `linkedfrom:` queries.

Example frontmatter:
```
places: 
  - "[[New York]]"
  - "[[Boston]]
```

Perhaps this is an Obsidain API thing that will be worked out before general release but wanted to mention it.

**Comment by esm7** [comment]
Seems like Obsidian does recognize these as links and it should reflect in the API, even if Map View should do something additional. I'll work on it.

**Comment by jonjnicholson** [comment]
I'm having a similar issue, but where I have a parent trip note, e.g., "Rocky Mountain NP 2023" and I have journal entries that have a "trip" property that backlinks to the trip note. Would be lovely to be able to see a map of all the notes that linked to the trip.

**Comment by The-Noah** [comment]
I fixed this in #252, we're just waiting for a new release. Hope it helps!

**Comment by esm7** [comment]
Sorry for the holdup, I was hoping to fix a few more issues before issuing a new releases but was not yet able to come around to it. In order to not delay things further, I'll make a release next week either way.

**Comment by esm7** [comment]
In spite of this being a major reason I released 5.0.3 last week, I didn't add it to the changelog :facepalm: But it's there!
