### ISSUE TITLE
Remove markdown formmating from popup

### ISSUE THREAD

**Issue by UjwalNK** [esm7/obsidian-map-view#20]
On hovering over a marked point in the map view, it shows all the markdown text, would it be better to display only the previewed content instead of markdown formatting? 

![Screenshot from 2021-08-06 14-54-59](https://user-images.githubusercontent.com/44840915/128489304-3ac0ec26-7232-4da4-ab80-2e7a7d8a27b3.png)

That is: Would it be better to remove all the markdown formatting and other stuff from the popup and just show the point name as 
`Hadima Temple` in Bold instead of `] [Hadima Temple` `- [ ] [Hadima Temple](geo:...)`

My markdown File:
```markdown
---
locations:
---

- [ ] [Hadima Temple](geo:32.29014729986857,77.18082236639961)
```

**Comment by esm7** [comment]
There are two different things here:
1. The bottom line of what you see is the snippet, which has a configurable size. You can make it 0 in the configuration and just get the file & point names. If you do like the snippet, I'm not sure it's beneficial to remove the markdown formatting without making it an actual preview. What do you think?
2. In the middle line you get `] [Hadima Temple`. That's not markdown formatting -- it's a parsing error :) In that line you are supposed to get just the point name, but seems like the checkbox causes a bug. Will fix!

**Comment by esm7** [comment]
Closing, this is now irrelevant with the new note previews :sunglasses:
