### ISSUE TITLE
Open in New Pane asks to open link

### ISSUE THREAD

**Issue by TheFibonacciEffect** [esm7/obsidian-map-view#200]
If I click on a geo link (eg: `[Cathedral de Santa Maria](geo:40.41580041174021,-3.7153555949265544)` ), the map is opened in a new pane, but I also get asked if I want to open a link to [geo:40.41580041174021,-3.7153555949265544](geo:40.41580041174021,-3.7153555949265544), which is not intended.

**Comment by TheFibonacciEffect** [comment]
![image](https://github.com/esm7/obsidian-map-view/assets/58665956/e11eeb4b-f1f0-4fab-a09d-bd3a40bce821)
Here is what I mean, I get led to the website https://wheelmap.org/search

**Comment by esm7** [comment]
I am unable to recreate this, so more details would be helpful.
1. What Obsidian version?
2. What OS?
3. Are you using Editing or Reading view?
Overall, if you can make a short video snippet of the issue, it would be helpful, as I might see in it some detail that I didn't think about.

**Comment by TheFibonacciEffect** [comment]
Hi, sure
1.Version         : 1.3.7-1
2. Arch Linux
3. I am using editing view but the issue appears with both, I think.
![output](https://github.com/esm7/obsidian-map-view/assets/58665956/f6e5ee52-f88f-482e-968b-290a7ef66ae0)

I am using ctrl+shift+click to open the link

**Comment by TheFibonacciEffect** [comment]
The issue also appears when I just open liks normally, considering that I have "open in 2nd pane and keep reusing it" set. 
I am not getting asked if I want to open a link when I open the map view for the first time, but when I reuse the map subsequently I get asked every time.

**Comment by nio101** [comment]
Hello,
I have the very same problem on windows... Makes the all thing unusable... :s

**Comment by esm7** [comment]
Hi all,
I was unable to find time to work on Map View in the past weeks (there area where I live is a war zone now :( )
Hopefully things will calm down reasonably soon and I'll be able to work on this and other issues.
The "Handle geolinks in notes" feature is not perfect yet, and until I manage to work on it and find a way to improve it, if you find it more harmful than good, note it can be turned off in the settings.

**Comment by TheFibonacciEffect** [comment]
Dont worry, its not something that perticularily restricts my usage of the awesome plugin you made! I also sincerely hope that you and your family and friends go through this unharmed. I dont know what to say as I cant imagine the suffering and pain of going though a war, but I wish you the very best!

**Comment by esm7** [comment]
Hopefully finally fixed in 5.1.0!

**Comment by TheFibonacciEffect** [comment]
Thanks a lot : )
