### ISSUE TITLE
Handling of apartment numbers

### ISSUE THREAD

**Issue by mgorfer** [esm7/obsidian-map-view#205]
I want to save the addresses of people in my obsidian notes. For sending post, the aparment numbers are also important.

In Austria, this is normally done via
| Data | Explanation |
|---|---|
| Frau |Title |
| Michaela Sommer | Name |
| Grünwaldweg 16/3/25 | Street, House/Staircase/Apartment Number |
| 81671 MÜNCHEN | Post Code, City |
| DEUTSCHLAND | Country |

I know that even the [OpenStreetMap Nominatim](https://nominatim.openstreetmap.org/) does not support these apartment numbers in the search.
But is there a recommended way to keep the apartment numbers included in my obsidian files?

My workaround for now is to first just use an address which can be found by obsidian-map-view.
`[Grünwaldweg 16, Bad Gleichenberg 8344, Austria](geo:46.860985400000004,15.91317099779346)`

And after the generation of lat/lon I add additional details I need. For examples
`[Grünwaldweg 16/3/4, Bad Gleichenberg 8344, Austria](geo:46.860985400000004,15.91317099779346)`

I am totally fine with this, but I wonder if this is the best approach?

**Comment by esm7** [comment]
Sorry for the late reply, but I also don't have much better ideas than you do here :)
The only thing I have to add, is that at least for me, I sometimes take a more minimalistic approach to the geolink name, and put in there what I want to actually see in the map -- e.g. the person name. I then put other details like the address in a line below. Sometimes I do the same with bullets. This includes addresses, opening times, phone numbers and pretty much anything else I want to quickly access based on the location.
