### ISSUE TITLE
[Bug] Notes with slashes in name not created when using "New geolocation note" command

### ISSUE THREAD

**Issue by ParkerRobb** [esm7/obsidian-map-view#207]
I have the plugin set up to use `{{query}}` as the "New note name format". When that query includes slashes, like the following example, hitting `enter` to create the new note does _not_ create a new note like it should.

![image](https://github.com/esm7/obsidian-map-view/assets/62605621/7b5acf07-6a2c-4862-8e5f-c0b7d613a289)

**Comment by ParkerRobb** [comment]
Since filenames cannot contain `/` or `\`, this plugin should change that to a different character, say `-`, when creating new notes.

**Comment by esm7** [comment]
Completely right. Will fix.

**Comment by esm7** [comment]
Fixed in 5.0.0.
