### ISSUE TITLE
Set new map source as default

### ISSUE THREAD

**Issue by jerrysoft-x** [esm7/obsidian-map-view#213]
I've added new map source and it works.
However I didn't find anywhere in the setting to set the new map source as default, and thus whenever I click "Show on map" it always open CartoDB as default map source.

BTW, I noticed that in different map sources, the same location coordinates will show some drift on the map, like between CartoDB and Google Maps, and it is a bit annoying.

**Comment by esm7** [comment]
If you expand the Presets drop-down in the map, you should see a "save as default" button that should do what you're looking for.
