### ISSUE TITLE
Display all linked nodes as graph on map

### ISSUE THREAD

**Issue by timjore** [esm7/obsidian-map-view#215]
As a user that needs to be able to visualize geospatial relationships as well as associative relationships, I would like to be able to toggle a switch in the configuration of the Map View plugin that enables the display of any nodes linked to nodes with geolocation information. This would provide a hybrid map + graph view: geolocated nodes are located on the map according to their coordinates (current functionality) and any nodes linked to them are displayed as a graph (default Obsidian graph functionality). Notes:

- Nodes w/ geolocation information display as geo markers (current functionality)
- Nodes w/o geolocation information display as circles (default Obsidian functionality)
- Graph display could be controlled by standard Obsidian graph filter/forces/etc. configuration

**Comment by esm7** [comment]
Someone requested it in the past already so sounds like it's certain a desirable feature, but weighting so many other features I'd like to add, and currently only me working on this project, I'm afraid it will remain a low priority for now :(

**Comment by esm7** [comment]
A partial version of this (that only shows the map markers) is now in 5.0.0.
