### ISSUE TITLE
Auto-center map to contain all queried locations

### ISSUE THREAD

**Issue by fbuchinger** [esm7/obsidian-map-view#222]
Can you offer an option to auto-center the map? Given a few geo-locations are provided in the map, your plugin could automatically compute the bounds that contain all these locations and then zoom the map automatically to it. (cf. https://leafletjs.com/reference.html#map-fitbounds)

This frees the user from manually specifying the center of the map.

**Comment by esm7** [comment]
Have you tried the "map follows search results" setting? I think it should do what you're asking for.
