### ISSUE TITLE
Feature Request - Modify Add an embedded map command to use location frontmatter property

### ISSUE THREAD

**Issue by sieminglyblue** [esm7/obsidian-map-view#228]
Been using MapView to help me map out all the restaurants I want to record. 

I've made a Restaurant template and QuickAdd button that upon creation, use the "Add geolocation (front matter) to current note, so that this rolls up into an overall MapView page.

However in each Restaurant page I'd also like to have a mini-map of the restaurant embedded for contextual awareness of where that restaurant is and I'm finding it difficult to figure out a way to do this with macros etc.

Am I missing something? Having this would be a great way to reuse the information already in the frontmatter property

**Comment by sieminglyblue** [comment]
Ah yep that works thanks! Is there a way to auto-centre around that location as part of the template?

**Comment by esm7** [comment]
Hmmm, good question. I think that if you have "Map follows search result" turned on in the plugin settings, it would work for that too. But that's a setting for the entirety of Map View and not just a specific map. It makes a lot of sense to make that something that is saved as part of a specific map and not a global setting.
