### ISSUE TITLE
Adding on 5.0.0

### ISSUE THREAD

**Issue by Comprehensive-Jason** [esm7/obsidian-map-view#231]
When I run the command, "Map View: Add geolocation (front matter) to note", nothing happens and the following error appears in console: 
![image](https://github.com/esm7/obsidian-map-view/assets/68677082/907f1c72-0adf-438d-8571-bf0c73531f77)

This was tested in Sandbox.

**Comment by esm7** [comment]
Thank you for catching this. Found the issue and will post a fix today.
