### ISSUE TITLE
Updating location in inline geolinks results in deletion of the following tag

### ISSUE THREAD

**Issue by JoKo1959** [esm7/obsidian-map-view#234]
I use tags directly after inline geolinks, 
e.g. [Paris](geo:48.8534951,-2.3483915) tag:Town
When I move the marker in the map, the geo-coordinates change as desired. Thanks for this new feature. However, while updating the geolocation, the tag is deleted. Is there any help for this?

**Comment by esm7** [comment]
That's bad! Will fix.

**Comment by esm7** [comment]
Fixed in 5.0.2.
