### ISSUE TITLE
Locations not showing markers on map

### ISSUE THREAD

**Issue by W1BTR** [esm7/obsidian-map-view#240]
I chose a random PD station near me as an example.

I can click "Embed a Map View" and type in a location, such as Pepperell Police Dept in Mass. It embeds this:
```mapview
{"name":"Default","mapZoom":8,"centerLat":42.6655787,"centerLng":-71.58588154526726,"query":"","chosenMapSource":0,"showLinks":false,"linkColor":"red"}
```
It is focused on the right area, but I see no marker of the location. I tried manually adding in a location to the document by adding:

Location: [42.6655915,-71.5884436]

But still, no markers.

Am I just misunderstanding the documentation?

**Comment by esm7** [comment]
Yes :) Embedding a view shows a map of a designated area inside a note, and if your vault happens to have markers in this area, they will show up. I'm not sure this is what you intended to do.
To add a geolocation, e.g. Pepperell Police Dept, open the Obsidian command palette and choose "add inline geolocation link" or "add geolocation (front matter) to current note". An alternative is to open Map View (with the map marker icon in the Obsidian shortcuts bar), search for the place you want, then click one of the "new note here" or "copy geolocation" options.
