### ISSUE TITLE
Map should show locations of geotagged notes that are referenced in Properties

### ISSUE THREAD

**Issue by brettroy** [esm7/obsidian-map-view#245]
I have a note LocationA that has a property location on it
This location shows up in a map when I focus in Map View - All good

If I create a new note and add LocationA as a link within the new note
This location shows up in a map when I focus in Map View - All good

If I create a new note and add LocationA as a property on the new note
**This location does not show up in a map when I focus in Map View** 
My thinking is that it should show in that case also

**Comment by esm7** [comment]
Can you elaborate on the 3rd part, how you "add LocationA as a property from the new note"? The source view of the front matter would help clarify the issue I believe.

**Comment by brettroy** [comment]
Instead of adding the LocationA as a link in the note, I add it into a Property of type List
Thanks for asking for clarification!

**Comment by esm7** [comment]
Can you show via a screenshot or copying & pasting the front matter what you mean? I still don't fully understand, sorry :(

**Comment by The-Noah** [comment]
@esm7 I'm having the same issue, here is a screenshot of my front matter:
<img width="374" alt="image" src="https://github.com/esm7/obsidian-map-view/assets/35819660/12e582cf-1625-437c-a121-223283c9fd70">

**Comment by esm7** [comment]
I'll make sure to address this in the next slot I'll have for maintaining the plugin.

**Comment by brettroy** [comment]
Thanks @The-Noah !!!

**Comment by brettroy** [comment]
Here si mine @esm7 

First note - The location ...
![image](https://github.com/esm7/obsidian-map-view/assets/4580444/83b629bc-5a9b-4db2-9981-e8edc4cfa271)

Second Note - The Note I want to use the location in ...
This one has the linked note as part of the document
![image](https://github.com/esm7/obsidian-map-view/assets/4580444/1efa20c3-ad89-43d9-a0cc-ef1ae0707be7)
This renders great - Awesome!!!
![image](https://github.com/esm7/obsidian-map-view/assets/4580444/02a9058c-e4a4-4fb5-ab3e-9d3cf4915c46)

Move the linked not into a property
![image](https://github.com/esm7/obsidian-map-view/assets/4580444/4b3f14c7-b258-46ee-bf11-5a1df93deeb4)
Pin no longer shows
![image](https://github.com/esm7/obsidian-map-view/assets/4580444/eac5119b-caeb-4104-80de-b24b1debf5f6)
