### ISSUE TITLE
Exporting Map view to html pages?

### ISSUE THREAD

**Issue by elFlashor** [esm7/obsidian-map-view#250]
First of all thank you for this plugin, it is great and I love it so far!

This is not an issue nor a feature request (although it could become a feature request if desired, that would be rad :D ) but more a request for information and help regarding a way to export the maps of my vault into any shareable format over the web.
Would anybody know of a way to generate html pages with an embedded map and all the notes of the vault, that would basically work the same way it works in Obsidian?
Would that even be possible directly with what you have already done, or would this require embedding a separate map and just exporting the notes locations separately? (I do not know much about how maps embedding work)

Thank you for any information you can share light on! :)

**Comment by esm7** [comment]
Hi, sorry for the long time to reply.
Unfortunately I come with bad news: I'm not aware of a way to do what you're asking. In theory, if Obsidian Publish would offer a plugin API, Map View could work within it. But that's not the case at the moment.
It might also be possible to do a dedicated HTML export mechanism in Map View, but it would require a whole lot dedicated infrastructure to work independently outside of Obsidian, which I don't think I can prioritize :(

**Comment by elFlashor** [comment]
Hello!
Thank you for your answer, it was more a shot in the dark just in case than anything else... In the end I rolled out my own solution to parse all my md files and generate the data for a leaflet map in geojson, works like a charm and I am very happy with the result!
Good luck with the future of this plugin, it's a little gem!

**Comment by elFlashor** [comment]
Closing the issue :)
