### ISSUE TITLE
Using custom property instead default location does not work

### ISSUE THREAD

**Issue by AndreasSachs** [esm7/obsidian-map-view#251]
Thanks for the plugin!
I wanted to use "coordinates" as a property for lat and long, because I was already using the "location" property for a different purpose. I've adjusted the settings, but the map didn't show any locations.
In the function getFrontMatterLocation(file, app, settings) the line const location = new leafletSrc.LatLng(frontMatter.location[0], frontMatter.location[1]); seems to still use the location property instead of the custom one.
Changing it to const location = new leafletSrc.LatLng(frontMatterLocation[0], frontMatterLocation[1]); seems to work

**Comment by esm7** [comment]
Sorry about that. Will add the fix to the next release.
