### ISSUE TITLE
[Feature request] - Map View query mechanism should be able to filter by properties

### ISSUE THREAD

**Issue by pelegm** [esm7/obsidian-map-view#257]
As I mentioned in #255, I think it would be very useful to allow queries such as `[propertyname:propertyvalue]` in the Map View Filters section. It should be in a way that resembles the Obsidian query syntax, so, e.g., if property `foo` has value `[[Bar]]` or a list of values, one of which is `[[Bar]]`, then `[foo:Bar]` should consider it.

If this is too much to implement, perhaps it would be easier to allow `linkedto:` to also read from property values (e.g., if the property `foo` has value `[[Bar]]` or a list of values, one of which is `[[Bar]]`, then `linkedto:"Bar"` should consider it.

**Comment by zakj** [comment]
@esm7 Would you be open to a PR here? I put together a quick hack that seems to work: https://github.com/esm7/obsidian-map-view/compare/master...zakj:obsidian-map-view:property-queries. Looks like I'd also need think about updating the query suggester.

**Comment by esm7** [comment]
Would definitely love a PR here. I'm unsure about the most suitable syntax that would be both consistent with the rest of the Map View queries and how Obsidian properties work. I understand you went for a syntax of the form `[property:value]`, I never used these searches in Obsidian but it seems like Obsidian supports (and suggests by default to use) quotes -- `["property":"value"]`, I think it should at least be supported even if not the default.

**Comment by zakj** [comment]
Yes, Obsidian uses quoted property name or value to indicate an exact match—unquoted name or value can partially match. I'll factor that into my implementation.
