### ISSUE TITLE
Bug Report: Paste as Geolocation not working

### ISSUE THREAD

**Issue by nhan000** [esm7/obsidian-map-view#260]
Using the Paste as Geolocation feature as [described in Readme docs](https://github.com/esm7/obsidian-map-view?tab=readme-ov-file#paste-as-geolocation) doesn't work. Clicking "Paste as geolocation" doesn't do anything.
![image](https://github.com/user-attachments/assets/97b8be35-92eb-4cf4-915a-4b275996c1be)

I've tried it on the Sandbox Vault. 
Obsidian 1.6.7, Map View 5.0.2, Windows 11

**Comment by The-Noah** [comment]
This was fixed in #254, but there hasn't been a released since it was merged.

**Comment by esm7** [comment]
Released!

**Comment by nhan000** [comment]
Minor point: It should also be in the command prompt as well in addition to the right click menu?

<img width="201" height="105" alt="Image" src="https://github.com/user-attachments/assets/39f1550e-c092-4988-ab47-d6706edf32f1" />

**Comment by esm7** [comment]
If by command prompt you mean an Obsidian command (available from the command palette), it is not, but I see why it's useful. Will add that if you find it useful.

**Comment by nhan000** [comment]
Yes that's what I meant, an Obsidian command in the Command Palette.
