### ISSUE TITLE
Map viewer has dark grids

### ISSUE THREAD

**Issue by JoaoAmaro2001** [esm7/obsidian-map-view#261]
Basically shown in the printscreen:

![image](https://github.com/user-attachments/assets/e27e5216-0a40-4b0b-82e7-6aafa4b4835c)

**Comment by esm7** [comment]
Wow I've never seen anything of the sort, can you share details about your setup?
Obsidian version, Map View version, platform (iOS? Windows? Mac? Android? Linux? What kind of device?), do you have any special themes or other plugins that may interfere?

**Comment by esm7** [comment]
It's a bit of a shot in the dark as I know nothing about your system, but my best guess at this point is some custom theme that is setting global margin/border rules that affect map tiles.

**Comment by JoaoAmaro2001** [comment]
Processor: 13th Gen Intel(R) Core(TM) i7-13705H   2.40 GHz
RAM: 16,0 GB 
Architecture:  x64
OS: Windows 11 Pro
Version: 23H2
----
obsidian: 1.6.7
map view: 5.0.2
----
Community plugins i use:
![image](https://github.com/user-attachments/assets/079bf0a8-5e6e-4ad4-a860-8a6934a437b6)
----
Themes:
![image](https://github.com/user-attachments/assets/f41e7e50-f714-45a0-a846-4516552a3d2d)
I use the obsidian gruvbox theme but I changed to the default and the problem persisted.

It should be noted that I did not have this problem when i first installed the plugin. However, I am not sure what actions i took that resulted in this issue. Thanks!

**Comment by JoaoAmaro2001** [comment]
I figured out the problem! It was a css snippet I was using to format figures! 

```
img {
    
    display: block !important;
    margin-left: auto !important;
    margin-right: auto !important;
	max-width: 100%;

	padding: .5em;
	margin: .5em;

	& .callout-icon {
		display: none;
	}

	& .callout-title {
		padding: 0;
		margin: 0;
	}

	& .callout-content {
		--callout-content-background: rgba(0, 0, 0, 0);
		padding: 0;
		margin: 0;
		border: none;
		box-shadow: none;
	}
}

.markdown-source-view.mod-cm6 .cm-content > * {
    margin: auto auto !important;
}
```

Thanks for the help anyways!
