### ISSUE TITLE
[Question] Map of Daily-Locations in Daily-Note

### ISSUE THREAD

**Issue by Volker-brdb** [esm7/obsidian-map-view#271]
Hello,

I have not yet been able to find out whether or how this works. That's why I'm asking here.
My idea is to list all the places I have been to during the day in the daily note. And to have a map in the daily note that shows all these places (and only these).
I can do that manually. But I would like to store the map in the Daily Note template so that it is automatically there for the respective day without me having to do anything manually. 
Is that possible?

Translated with DeepL.com (free version)

best regards
Volli

**Comment by esm7** [comment]
Hi,
That's definitely possible to set up.
See here: https://github.com/esm7/obsidian-map-view?tab=readme-ov-file#advanced-additional-options

**Comment by Volker-brdb** [comment]
Ah, thank you for pointing me in the right direction.
Just a hint, in the docu is a little error, missing one " -> must be "linkedfrom:\"$filename$\"" instead of "linkedfrom:\"$filename$\"
