### ISSUE TITLE
Customize icon for inline geolocation link?

### ISSUE THREAD

**Issue by travissanderson** [esm7/obsidian-map-view#275]
Is there a way to have multiple geolocation links in a note that have different icons? If I am understanding the documentation correctly, that is not the case and you instead need a collection of notes where each note is either a unique location or a group of locations that all have the same icon. Maybe I am not thinking like Obsidian and should be using more notes, but my first instinct was to create a single note for a location I wanted to map out and tried to add different types of interesting points to it.

**Comment by esm7** [comment]
Hey Travis, I'm not next to a computer so can't easily send you a
documentation link, but look up in the README about inline tags, in the
tag: format. So you can have it either way - inline geolocations with
different icons, or notes that contain locations with the same tags (or a
combination).

**Comment by travissanderson** [comment]
Ah yes I found it in the https://github.com/esm7/obsidian-map-view?tab=readme-ov-file#understanding-map-view-parsing-location-data section. I should have read from top to bottom instead of skipping to icons! Thanks.
