### ISSUE TITLE
Error with Stadia maps sources

### ISSUE THREAD

**Issue by Henrydice** [esm7/obsidian-map-view#278]
Hi,

First of all, many thanks for this amazing add-on !

I'm trying to use a source map from stadiamaps that I've found [here](https://wiki.openstreetmap.org/wiki/Raster_tile_providers) but the tiles url doesn't seem to work. 

First I had a 401 error : Invalid Authentication like in this screenshot.

![Screenshot_2024-09-24_at_01 24 35@2x](https://github.com/user-attachments/assets/47b50861-63d1-4d90-9603-1b2dface397d)

Then, I created an API key on the website and added to the url following the rules [here](https://docs.stadiamaps.com/authentication/), but the map wouldn't load and I would get this error message : "Map view: unable to load map tiles. If your Internet access is ok, try switching the map source using the View controls."

Any idea how to solve this ?

**Comment by esm7** [comment]
Can you share how you set up the map source in Map View (you can replace the API key with ABCD or similar)?

**Comment by esm7** [comment]
It seems like everything is set properly. Perhaps there are more clues in the Development Console (Ctrl+Shift+I or Cmd+Shift+I)?

**Comment by esm7** [comment]
In Obsidian. You can open it with Ctrl/Cmd+Shift+I and it might contain a more useful error.

**Comment by esm7** [comment]
The error shown in the log is not the authentication error we originally suspected, but a "404 not found" error, which is a different story. Seems like the Stadima tiles URL is not working as expected. If you just enter one of the tile URLs in the browser, can you see the tile? If not, maybe contacting Stadima (or digging deeper in their documentation, forums or whatever is available) should be the next step.

**Comment by esm7** [comment]
So it's now certain that the URL is wrong, and only Stadia can help with that :(

**Comment by esm7** [comment]
I tried to invest some more time into understanding how to use Stadia Maps but the only way I see to get an API key is to email them, is this how you did it or is there another way?

**Comment by esm7** [comment]
I decided to give it a go myself, made a Stadia API key and added the following to Map View as a map source:
`https://tiles.stadiamaps.com/tiles/stamen_toner/{z}/{x}/{y}.png?api_key=...` (very long API key)
This works!
Have you done anything different than I did?
![image](https://github.com/user-attachments/assets/4cf62878-7297-4a3c-88b9-afacdb1b249b)

**Comment by esm7** [comment]
That's great to hear, and nothing to be sorry about, I'm the one who wants to thank you for introducing me to Stadia Maps, they're amongst the most beautiful map sources I've ever seen!
