### ISSUE TITLE
URL template to allow multiple replacements

### ISSUE THREAD

**Issue by t3mujin** [esm7/obsidian-map-view#283]
Seems like the logic of parsing the URL for Custom "Open in" only is replacing the first occurrence, but it would be great to allow to replace all. An example, I was trying to set an URL for OsmAnd with a pin, so I have to set two sets of coordinates, one for the pin and other for the map itself, something like:
`https://osmand.net/map/?pin={x},{y}#9/{x}/{y}` 

But what's being sent to the browser is only the first set replaced

**Comment by esm7** [comment]
Already done, will be in the next release.
