### ISSUE TITLE
Keep the current map section (mapZoom, centerLat, centerLng) when filtering

### ISSUE THREAD

**Issue by JoKo1959** [esm7/obsidian-map-view#287]
Thank you for the useful app. Here is my question / wish: I have a map view of Central London with many defined places; for example restaurant, museum, viewpoint. The geolocations for these are stored in many different files across my Vault. If I'm looking for a restaurant nearby, I can search for tag:location/restaurant in the top left-hand corner under Filters. However, the map section then changes and all the restaurants I have defined are displayed worldwide. It would be nice to have an option to keep the current map section (mapZoom, centerLat, centerLng) when filtering. Thank you.

**Comment by esm7** [comment]
Turning off "Map follows search results" in the plugin settings (first line in the page) should do the trick. Hope I understood correctly and that's what you mean :)

**Comment by JoKo1959** [comment]
Great; thank you so much!

Von: esm7 ***@***.***>
Gesendet: Freitag, 1. November 2024 10:41
An: esm7/obsidian-map-view ***@***.***>
Cc: Kornhuber, Johannes ***@***.***>; Author ***@***.***>
Betreff: Re: [esm7/obsidian-map-view] Keep the current map section (mapZoom, centerLat, centerLng) when filtering (Issue #287)


Turning off "Map follows search results" in the plugin settings (first line in the page) should do the trick. Hope I understood correctly and that's what you mean :)
