### ISSUE TITLE
Geolocation search for YAML location metadata

### ISSUE THREAD

**Issue by HEmile** [esm7/obsidian-map-view#29]
Hi, loving the new feature for geolocation search! However, I have all my location data in the `location` yaml key. Is it possible to have a command for inserting the geolocation there?

Also, I tried the functionality and could not get it to work yet, but this might be because I'm using the Insider Live Preview.

**Comment by esm7** [comment]
Will do.
Re Live Preview, I actually wrote this a few weeks back before it was released, so I didn't get to test it together (and I'm not using it myself). I'll take a look what could be preventing it from working there.

**Comment by esm7** [comment]
I think you will appreciate the just-released 1.2.0 update :)
