### ISSUE TITLE
FR: Open notes in separate pane

### ISSUE THREAD

**Issue by HEmile** [esm7/obsidian-map-view#3]
I often like to explore notes while navigating the view. However, there's currently no way to open a note from the view without closing the view (it opens the note in the same pane as the map view). It would be great if ctrl-clicking a note would open it in a new pane. Alternatively, opening notes can always be in a separate pane. I personally prefer this, but it goes against how the global graph view is currently designed.

**Comment by esm7** [comment]
That's a very useful feature. Will do.

**Comment by esm7** [comment]
I added this in the most generic and useful way that I could.
New settings were added for how to open a note by default, and Ctrl reverses the behavior.
Also, unless turned off in the settings, if a new pane was opened to display a note, the view tries to keep using that pane for new note opens as long as it's valid.

**Comment by HEmile** [comment]
Just tried it out, this is perfect, thank you!
