### ISSUE TITLE
Inline tags doesn't change icon

### ISSUE THREAD

**Issue by MicheleDeZen** [esm7/obsidian-map-view#30]
Hi, i am having some problems trying to define multiple points with different tags ex.
[Venice airport](geo:45.50353855,12.342579681064803) tag:dep-plane

The point shows up on the map but the icon does'n change

![image](https://user-images.githubusercontent.com/66516225/148234990-957e3481-3743-41e2-b408-fd6d8220b540.png)

I also would like to understand if i can define multiple points with different tags in the same note

Thanks

**Comment by esm7** [comment]
Turns out that the regex that matches inline tags (as opposed to note tags which uses the built-in Obsidian system) doesn't take into account the dash character.
I'll fix it, but in the meantime, take into account that alphanumeric characters and an underscore should work.

**Comment by esm7** [comment]
Fixed in 1.1.0.
