### ISSUE TITLE
Separate tile set for dark mode

### ISSUE THREAD

**Issue by kepano** [esm7/obsidian-map-view#34]
It would be useful if a separate tile set can be specified for dark mode. This functionality has now been added to the Leaflet plugin.

Additionally it would be awesome if switching between light/dark mode would refresh the map with the appropriate tile set. 

Thanks for the great work!

**Comment by dummifiedme** [comment]
+1

**Comment by esm7** [comment]
To understand this better, do you guys regularly switch between light & dark, and there's a need for the plugin to choose the right tile set accordingly?

**Comment by dummifiedme** [comment]
> To understand this better, do you guys regularly switch between light & dark, and there's a need for the plugin to choose the right tile set accordingly?

Yes, I switch modes based on my surrounding (dark when I am inside, or light when I am out) and the lighting around. 
As we discussed in #33, we can have multiple tile set stored and one assined for each darl/light mode as well,. :)

**Comment by esm7** [comment]
Multiple tile sets is on the way, question is whether it makes sense that for each tile set, have a separate light & dark variants, and be able to switch between them automatically.
Is there a need, and is there a reference for a plugin that makes this choice automatically, so I can see what they're doing?
It's easy to check if Obsidian's current base theme is Light or Dark, but since the user can have any custom theme, I have no clue how to tell if such a theme is light or dark.

**Comment by dummifiedme** [comment]
> Multiple tile sets is on the way, question is whether it makes sense that for each tile set, have a separate light & dark variants, and be able to switch between them automatically. Is there a need, and is there a reference for a plugin that makes this choice automatically, so I can see what they're doing? It's easy to check if Obsidian's current base theme is Light or Dark, but since the user can have any custom theme, I have no clue how to tell if such a theme is light or dark.

@kepano could better explain about themes' dark and light mode, but I think they are also based on obsidian's light and dark modes.

As for light-dark sets for each tile, its not very critical for me. 

But having multiple tile sets could be used by having a command for each tile set.
Just an Idea:
**Each tile set could have**
- a name
- a tick option (whether to show in commands or not)
- dark mode link
- light mode link

If anyone of the dark or light mode links are missing, it will only load up whichever is present.
Also, we can make one of these sets as DEFAULT (that opens with `Open Map View` command)

**Comment by kepano** [comment]
Here is some reference code from my plugin System Dark Mode
https://github.com/kepano/obsidian-system-dark-mode/blob/master/main.ts

I think it is fair to assume that if the user is in Moonstone (aka light mode) the light tile set can be used and Obsidian (aka dark mode) the dark tile set can be used

The Carto tile sets provide a good test bed for this:

**Light**
https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png

**Dark**
https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png

**Comment by esm7** [comment]
Just released version 1.1.0 which adds support for this. Let me know how it works for you :)
