### ISSUE TITLE
I added a second mapsource and mapview could not save settings

### ISSUE THREAD

**Issue by zsviczian** [esm7/obsidian-map-view#41]
Obsidian froze and I had to terminate Obsidian in the windows task manager. When I restarted the new Map Source was there, and I had no more issues with saving settings.

![image](https://user-images.githubusercontent.com/14358394/151061864-4636b5a3-637d-4498-9e26-e9b40427c2cd.png)

![image](https://user-images.githubusercontent.com/14358394/151061486-e471b8b8-6cbe-450d-a9fe-0cb3bb6e8781.png)

**Comment by esm7** [comment]
I'm 90% sure I fixed this, but either way could not recreate; closing for now.
