### ISSUE TITLE
FR: More template options for new geolocation notes

### ISSUE THREAD

**Issue by HEmile** [esm7/obsidian-map-view#45]
Hi, thanks for the great new geolocation feature!

It'd be great if the title of the geolocation note could be your query for finding the geolocation. Eg: I query "Very cool restaurant", select the right geolocation, then it creates a new note called "Very cool restaurant" (where this can be done with eg the {{query}} template.

**Comment by esm7** [comment]
Sounds very useful, will add.

**Comment by esm7** [comment]
Added in 1.2.1.

**Comment by HEmile** [comment]
Thanks, that's awesome!
