### ISSUE TITLE
update existing note's yaml with location

### ISSUE THREAD

**Issue by trashhalo** [esm7/obsidian-map-view#46]
Its not clear to me how to do this with the current commands. I know I can put inline links but I'm trying to add a yaml/metadata location tag to an existing page.

I was able to do it by creating a new geo note. copying the line, then deleting the note. kind of high friction

**Comment by esm7** [comment]
What you can currently do is use "copy geolocation as front matter" from right-clicking the map, then paste the front matter in an existing note.
But - 1. I'm not sure the flow you're asking about starts from the map (maybe it's a location name you're interested at?), 2. It's surely not as streamlined as it can be.
I think it can be useful to add an "add geolocation (front matter)" action in a note's context menu, and also not a lot of work at this point. Will that help?

**Comment by trashhalo** [comment]
>I think it can be useful to add an "add geolocation (front matter)" action in a note's context menu, and also not a lot of work at this point. Will that help?

I think that would be amazing!

**Comment by esm7** [comment]
Added in the just-released version :)
