### ISSUE TITLE
[FR] Render map in note

### ISSUE THREAD

**Issue by dummifiedme** [esm7/obsidian-map-view#48]
Ability to render map in the note.

I think it is available with Leaflet plugin, but I don’t yet know how to use both together.

I would really like a way to render a region with filters into the note with a code block.

Something like this:

```
```mapview
region: [x0, y0, x1, y1]
filters: #caves, #lakes
` ` `
```

**Comment by esm7** [comment]
This goes against the concept of this plugin, which is to provide an interactive, searchable, filterable view of your notes through the prism of geolocations (like graph view does with links).
Adding a map to a note is a very different thing, and I'm leaving this to be the specialty of Obsidian Leaflet, which does it very well :) Better interoperability between the plugins (e.g. the ability to "export" a Map View view into a Leaflet note) is something I'm planning.
Also, I want to add "presets" for saving the active view and going back to it, maybe even through a link.

**Comment by dummifiedme** [comment]
> Better interoperability between the plugins (e.g. the ability to "export" a Map View view into a Leaflet note) is something I'm planning. Also, I want to add "presets" for saving the active view and going back to it, maybe even through a link.

Sure.
Leaflet does show the map well but it isn't as easy to use as MapView. 
Adding locations and linking notes to the map is way easier and intuitive in this plugin.

But yes, will try to see how to use both the plugins.

Thing is, there are MOC notes which if enriched with Map, it would be complete in a sense. Maybe if there is a sync between the map MapView displays and the Leaflet, it would make it work... :/

**Comment by esm7** [comment]
Gotcha, the flow of MOC notes is a great use case.
It just convinces me even further that the two plugins need to get better at working together, because I greatly believe in "do one thing well". Obsidian Leaflet is a great tool for embedding maps in notes, and I rather utilize this than imitate the very same abilities.
