### ISSUE TITLE
Bug: MapView opens up too far zoomed out

### ISSUE THREAD

**Issue by HEmile** [esm7/obsidian-map-view#5]
When I finished adding location tags to all my (relevant) notes, the MapView started opening like this (too far zoomed out)

https://user-images.githubusercontent.com/1289165/124168164-0eeffd00-daa5-11eb-8bfb-e57e100b39a8.mov

**Comment by esm7** [comment]
I saw this happening earlier today too! I'm working on making the plugin
load flow much more robust and that should take care of that too.

**Comment by HEmile** [comment]
I found this happened because I had one note with an incorrect longitude (2000+), which means it stretches out all the way. Oops! Maybe to prevent this, it's possible to sanitize inputs by computing the coordinates modulo the range.

**Comment by esm7** [comment]
Great, thanks!

**Comment by esm7** [comment]
Fixed.
