### ISSUE TITLE
Compatibility with Sliding Panes

### ISSUE THREAD

**Issue by Signynt** [esm7/obsidian-map-view#53]
When opening the note in a new pane from Map view it should open it in a new sliding pane if the Sliding Panes plugin is installed. Currently it creates a split view, which is not the typical behaviour.
Thanks for the cool plugin!

**Comment by esm7** [comment]
Until I manage to try it out, I'm wondering, does it work the way you expect if you set "Default action for map marker click" in the settings to "always open a new pane"?

**Comment by Signynt** [comment]
I don't know why I thought it wasn't working, but giving it another go everything seems to be as expected! 😄
