### ISSUE TITLE
Support for non-English inline tags

### ISSUE THREAD

**Issue by tdwinki** [esm7/obsidian-map-view#55]
When you set non-English tags to customize map markers, inline tags wouldn't recognise non-English texts as tags and custom markers wouldn't show. They seem to work fine in marker preview tester though.

**Comment by esm7** [comment]
Indeed the regex that parses inline tags did not take non-English text into account (which is funny when I think about it, because many of my notes are not in English either... Yet I never considered non-English tags :shrug: )
Will fix.
