### ISSUE TITLE
Mislocation

### ISSUE THREAD

**Issue by RenaudSav** [esm7/obsidian-map-view#57]
I've been looking for a GIS solution like this for a while, and was very thrilled to give Obsidian Map a try, but I have the following issue : 
after copy-pasting an address from Google Maps into Obsidian, the link in Obsidian leads to an point on the map or in Google Maps which is a few blocks off the right (original) address in Google Maps... I tried with several adresses, including my home. 
The Geocoding search provider is the default one (OpenStreetMap).

**Copied (original) address**
<img width="1654" alt="Copied (original) address" src="https://user-images.githubusercontent.com/98715539/155000905-9e9685b8-a948-4ff0-ba5f-4555ab9fbf38.png">

**Obsidian link**
![Obsidian link](https://user-images.githubusercontent.com/98715539/155000962-7dd64b75-9b20-457e-834a-b434664e8d76.png)

**Address to where the Obsidian link leads**
<img width="1842" alt="Address to where the Obsidian link leads" src="https://user-images.githubusercontent.com/98715539/155000983-9806528e-0dcb-4387-b832-5870c8e9ed91.png">

**Comment by RenaudSav** [comment]
Additional comment : here attached a screen capture showing the coordinates before/after geolocation conversion (geosearch). 
The coordinates are slightly different, why that ?

![Before:after geolocation conversion (geosearch)- ](https://user-images.githubusercontent.com/98715539/155003992-13152fd8-ecbf-49eb-ad3c-f84295a38178.png)

**Comment by esm7** [comment]
Hey,
There is indeed an issue with the parsing from Google Maps that somehow I didn't notice so far.
More than a bug, it's a misinterpretation of what the URL in Google Maps actually represents. Turns out that it does not represent the chosen location, but the active view, so the coordinates are off from where you meant by a distance that's relative to the zoom level.
Until I find a better way to accomplish the original intent, I recommend that you define a custom URL parsing rule for raw `lat, lng` coordinates: `([0-9\.\-]+), ([0-9\.\-]+)`
Then in Google Maps, don't copy the URL, but rather the coordinates of a point. If you right-click a point in Google Maps Web, the first entry in the popup copies the coordinates to the clipboard, and then you can use "Paste as Geolocation" in Map View (after defining the custom parsing rule above) to enter the location, or paste it to the box in "new geolocatio note".
Let me know if this works for you.

**Comment by esm7** [comment]
![2022-02-24_15-04](https://user-images.githubusercontent.com/10722656/155529634-a7e4187a-5ba1-49fc-a5a9-2725c56661bf.png)

**Comment by RenaudSav** [comment]
Hey,

Thanks for your answer 😊
> There is indeed an issue with the parsing from Google Maps that somehow I didn't notice so far.
> 
Yes, it’s not a concern when locating the Yellowstone National Park, only noticeable with precise urban addresses.

> More than a bug, it's a misinterpretation of what the URL in Google Maps actually represents. Turns out that it does not represent the chosen location, but the active view, so the coordinates are off from where you meant by a distance that's relative to the zoom level.
> 

I get it, though I tried both : copy from the URL, and copy from the pin on a map. Doesn’t work either.

> Until I find a better way to accomplish the original intent, I recommend that you define a custom URL parsing rule for raw lat, lng coordinates: ([0-9\.\-]+), ([0-9\.\-]+)
> 
Hmm.. this I don’t get this one, where and how should I set this ? 
I’m not a developer, just an average user, and not very familiar with html and URLs. 
So I don’t know how to define a custom URL pasting rule, and don’t understand the ([0-9\.\-]+), ([0-9\.\-]+) formula..
I need your help there.


Renaud Savignard
***@***.***
+33 (0)608223634

**Comment by RenaudSav** [comment]
I wanted to let you know that locations coordinates from OpenStreetMaps, once copied and pasted as raw text, then converted, are at the right location when opened... even when opened in Google Maps.

**Comment by esm7** [comment]
Hey Renaud,
To add a URL parsing rule, go to the plugin settings (under Obsidian's Settings -> Map View), then scroll down to the section named "URL Parsing Rules".
Click on "New Parsing Rule". In the Name field enter whatever you'd like (e.g. "Coordinates") and in the box named "Regex with 2 capture groups" copy this: `([0-9\.\-]+), ([0-9\.\-]+)`
After setting this, you should be able to copy raw coordinates from Google Maps and use the Paste as Geolocation function with them.

**Comment by RenaudSav** [comment]
Thanks,

I’ve set this rule and just tried :
- copy raw coordinates from Google Maps : OK
- paste as geolocation : I don’t have this option, only ‘basic' paste ? So I have to convert afterwards..
- convert to geolocation (geosearch) : off
- convert to geolocation : OK !

So it seems to be OK except that :
- paste as geolocation doesn’t work
- geoseearch conversion doesn’t work, but maybe it’s no more the option to choose ?

BTW, how is the right sparse rule selected for conversion ? I now have three (see attached).
According to the address format I guess ? 





Thanks for your help !!


Cheers


Renaud Savignard
***@***.***
+33 (0)608223634

**Comment by esm7** [comment]
Can you take screenshots of:
1. The new URL parsing rules as you set them
2. How your note looks after pasting the raw coordinates from Google Maps
And when you write "convert to geolocation: OK", what do you mean? Do you right-click the pasted text and "convert to geolocation" from the menu works?

To your question, the parsing rules are attempted by their order. If you copied the raw location from Google Maps, only the new (3rd) rule should match.

**Comment by RenaudSav** [comment]
> 
> Can you take screenshots of:
> 
The new URL parsing rules as you set them
How your note looks after pasting the raw coordinates from Google Maps
Hereattached pdf



Original GoogleMaps location (red pin) :

> And when you write "convert to geolocation: OK", what do you mean? Do you right-click the pasted text and "convert to geolocation" from the menu works?
Yes

**Comment by RenaudSav** [comment]
UPDATE

>> And when you write "convert to geolocation: OK", what do you mean? Do you right-click the pasted text and "convert to geolocation" from the menu works?
> Yes Sorry, in fact no : I paste as raw text, (no other option, see video : https://www.loom.com/share/193d44787e624722af56ab77648f958e)

**Comment by esm7** [comment]
The attachments didn't work.

**Comment by esm7** [comment]
Updated the default URL parsing and removed the faulty Google Maps one in version 1.4.0.
Thanks for the help with this!
