### ISSUE TITLE
Bug: Open Street Map is blocking requests for tile map

### ISSUE THREAD

**Issue by HEmile** [esm7/obsidian-map-view#59]
I haven't tried this in a while, but since today at least I'm not able to load the OSM tile map both in Leaflet and in Map view. I'm getting Access denied. See https://operations.osmfoundation.org/policies/tiles/ 

See: 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/1289165/158059022-b3cd6c9e-3189-4c44-bc36-5963c28fb5dc.png">

(Note: I also posted this for Leaflet here https://github.com/valentine195/obsidian-leaflet-plugin/issues/286 )

**Comment by rossoj85** [comment]
I just started having the same issue tonight.

**Comment by menagerie198** [comment]
I am also having problems. OpenStreetMap is not rendering at all on my desktop (I don’t use the mobile version). All my pins are there, but no map.

**Comment by esm7** [comment]
As pointed out [here](https://github.com/esm7/obsidian-map-view/issues/11), CartoDB is free (for up to 75K calls), anyone having issues should go to the plugin's settings, scroll to Map Sources and replace the OpenStreetMap URL with -
`https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png`
(or any of the other beautiful styles listed [here](https://github.com/CartoDB/basemap-styles))

I will issue an update that "violently" replaces OpenStreetView with CartoDB the first time it's launched.

**Comment by HEmile** [comment]
Thanks for the update! I just tried and CartoDB seems to work. 
You're saying it's free for up to 75K calls, which will last for a while but is not permanent. Do you think you have a recommendation for a more permanent solution?

**Comment by HEmile** [comment]
Ah, per month! That's a whole lot more than I had in mind ^^ I'll try that out for now, it doesn't seem to be as detailed as OSM but it looks pretty and satisfactory, thank you!

**Comment by HEmile** [comment]
Repost from @Valentine195 (Javalent) from Leaflet:

> It actually looks like OSM has blocked the default user agent sent by Obsidian: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.13.23 Chrome/91.0.4472.164 Electron/13.6.2 Safari/537.36
> 
> Not really a way around that, spoofing it is against the TOS. Guess OSM in Obsidian is dead.

**Comment by esm7** [comment]
The good news here is that I guess it means the Obsidian mapping plugins have gotten "too popular" :)

**Comment by esm7** [comment]
As of 1.4.0, CartoDB is now the default tile source.
