### ISSUE TITLE
Feature request: Filter multiple tags

### ISSUE THREAD

**Issue by timtester-boop** [esm7/obsidian-map-view#67]
It would be nice if it was possible to filter multiple tags in map view mode. I have notes containing the tag of a month ("#june") and some of them also contain tags like "#hotel". Is there a way to show only notes that contain both "#june" and "#hotel" when showing the map? When you select multiple tags, it seems it searches for notes containing "#june" OR "#hotel" - i'm looking for a way to show notes containing "#june" AND "#hotel". Thanks a lot in advance! 😊

**Comment by gentlegiantJGC** [comment]
Is the SearchComponent class the same as the filter entry in the graph view?
If it is I think it would make sense to switch to that.
That way Obsidian can do the work to find the files and it will support OR and all the other things that it supports without any extra work.

**Comment by esm7** [comment]
`SearchComponent` is unfortunately just a text box with an X, it does not offer any search functionality. I've asked the Obsidian devs to open some search functionality in the API for a long time now (https://github.com/obsidianmd/obsidian-api/issues/22).
I've given up and spent lots of time to rewrite it from scratch, allowing search operators, logical operators, auto-suggest etc.
I'm in advanced stages (only README updates are missing) of releasing a major 2.0.0 version of Map View with this big new functionality.

**Comment by esm7** [comment]
Added in the just-released 2.0.0 version.
