### ISSUE TITLE
Would it be better to show the name of point1 comment rather than the file name

### ISSUE THREAD

**Issue by zhl111** [esm7/obsidian-map-view#7]
Mouse click on the point shows the file name but not Hudson River
![image](https://user-images.githubusercontent.com/29135984/125545810-c689fb76-16b2-4b09-a1e4-8e4ce2ab78f6.png)

Multiple attractions in one area, only file names are displayed, making it difficult to find attractions
![image](https://user-images.githubusercontent.com/29135984/125550613-3e33f8e8-e32e-43e2-b393-5712d23e26c9.png)

**Comment by esm7** [comment]
I agree, this is greatly worth improving. I'm just not sure how to do this well with inline locations. The format you chose, to put a name in a line above the location, is not some standard that will be suitable for everybody. Perhaps the most useful thing to do is to show a snippet of the note around the location.

**Comment by esm7** [comment]
I think that the note snippet functionality in the new release solves what you needed :)
