### ISSUE TITLE
White bubble when overing icon on map

### ISSUE THREAD

**Issue by Darkbluetest** [esm7/obsidian-map-view#75]
Hi,

The preview note when overing the icon is fine, but the white bubble that appears also when overing seems like unnecessary if preview appears. Would it be possible to add an option to choose also if we want the white buble to show up or not?

Tx

**Comment by esm7** [comment]
I can easily make it optional, the problem is that I was unable to find a way to show the note name in the preview (which Obsidian completely manages by itself), so without that extra bubble you'd get a completely anonymous file preview. That's the reason for the annoying duplicity.
Is it useful to enable turning it off?

**Comment by Darkbluetest** [comment]
I understand. 

As far as I know, the white bubble only shows name of note and below, the place, if the location is defined inline. Then I may suggest:

-Would it be possible to make the bubble to have the same width than the note preview window? If so, then could it be possible to place it exactly (touching) above the preview window? I am trying to suggest a way to fake it, i.e. to put the bubble just as a piece glued above the preview window, so to give the impression it is a single entity...

If too complicated, or not possible then, at least, I would suggest:

- to remove the .md extension from the name
- format it a bit better: put the name in a larger font, and maybe followed by the location in the same line in a smaller size and between parenthesis or brackets, just to make the bubble a single line, so the bubble is perceived as just for that, to show the name. Alternatively, if it is preferred to keep them in two lines (name and location), then in addition to adjust the font sizes, styles (whatever) to horizontal center both, name and location, and to reduce the interline space and margins). 
- Make it change color with Obsidian (Dark, Light modes)
- Make the corners of the bubble more like the theme, if possible.

Not sure about to add an option to turn it off. I have a title/name in the first line in some of my notes (so I can ID them in preview), but not in all of them. I am not sure.

**Comment by Darkbluetest** [comment]
I correct my last line, it might be useful to add an option to disable it, for people using plugins like "Hover Editor" or similar that replaces/improves the core plugin "Page Preview", and which shows nicely the name of the note at the top of the preview window. So, if possible I would add the option to turn it off too.

**Comment by esm7** [comment]
Added in the just-released 2.0.0 version.
