### ISSUE TITLE
Google API Not working?

### ISSUE THREAD

**Issue by Reseta12** [esm7/obsidian-map-view#76]
Not a coder, but I appreciate this plugin and would like to use it better, but for some reason, my API key doesn't seem to work with the plugin. Not very familiar with APIs, and regex, so would appreciate any help with this.

Is there some detailed procedure that I'm currently missing? How exactly do I use my API Key for Google Maps geocoding? Thanks.

**Comment by esm7** [comment]
Sorry for being unable to help on a timely manner, did you close this because you managed to fix it?
