### ISSUE TITLE
Renaming a file duplicates map pin

### ISSUE THREAD

**Issue by gentlegiantJGC** [esm7/obsidian-map-view#77]
When you rename a file, it creates a new pin and does not remove the old pin.
This leads to multiple pins at the same location when there is only one file.

It seems a step is missed somewhere that removes the old pins when a file is renamed.

**Comment by esm7** [comment]
It seems like my response here didn't register :thinking: 
Which version of the plugin are you using? This was supposed to be fixed in 1.5.0.

**Comment by gentlegiantJGC** [comment]
I thought I was running from the main branch but I forgot you need to compile typescript.
I am getting this error when compiling.
![image](https://user-images.githubusercontent.com/11940194/167377658-a1d6d39d-aaff-4393-abde-18d11cba040e.png)

**Comment by gentlegiantJGC** [comment]
I have just fixed the compile issue in #79 and can now confirm that the original issue has been fixed.
