### ISSUE TITLE
Marker duplication bug

### ISSUE THREAD

**Issue by gentlegiantJGC** [esm7/obsidian-map-view#85]
If the same geo url appears twice in the same file it causes the number of pins to increase each time the map is updated.

I think this is a bug with the way you unload markers. It might make sense to unload all markers from a file when that file is changed or deleted rather than having to check if the marker is the same as other markers.

Put this in a file and move the map around.

```md
---
locations: 
---
[](geo:51.50875957008922,-0.07710009813308717)
[](geo:51.50875957008922,-0.07710009813308717)
```

**Comment by esm7** [comment]
Fixed in the latest 2.1.x release.
