### ISSUE TITLE
Feature request: Allows multiple latitude and longitude coordinates to be displayed after the location in yaml

### ISSUE THREAD

**Issue by Xieleilab** [esm7/obsidian-map-view#86]
Allows multiple latitude and longitude coordinates to be displayed after the location in yaml, which means that one note can create multiple pins on the map at the same time

**Comment by esm7** [comment]
Have you looked into inline location URLs? These give you the same ability (multiple pins in a note), just not based on the front matter.
Extending the front matter format will require many changes in Map View and I'm wondering if it really has a major benefit over inline locations which can also have dedicated link names and their own individual tags.

**Comment by Xieleilab** [comment]
thanks a lot! besides, another little question is that can the appearance of the markers on the map  be distinguished by the tags in corresponding notes? Such as different color or shape. thanks!
