### ISSUE TITLE
【Feature request】tag filter

### ISSUE THREAD

**Issue by Xieleilab** [esm7/obsidian-map-view#87]
in the filters for tags,the function "quick add tag" can only select the needed tag in the whole list provided, Whether it can be set as a search box, and for multi-level tags (for example, # landscape/asia/lake,), only part of the text can be entered to display all the matching results.（this function is already popular in obsidian）,thanks a lot!

**Comment by esm7** [comment]
That (and much more) will be in the upcoming 2.0.0 version.
