### ISSUE TITLE
【feature request】modification for saved view with name unchanged

### ISSUE THREAD

**Issue by Xieleilab** [esm7/obsidian-map-view#91]
the function "save the current view" is great! but after i save a view ,i can not modify it with the name remaining unchanged

**Comment by esm7** [comment]
This may be a little counter-intuitive, but if you "save as" and give the exact same name, you will see "Clicking 'Save' will overwrite an existing preset", and when you click Save it will modify the preset rather than create a new one.
I will work on making this more discoverable.
