### ISSUE TITLE
Quick Search is not working for even famous cities 

### ISSUE THREAD

**Issue by dummifiedme** [esm7/obsidian-map-view#93]
I had been using hotkey for "Convert location to Geolocation" for a while now, and suddenly it stopped working for even famous cities.
Is there some reason behind it? I had updated the plugin today.
![Screenshot_20220521_094022](https://user-images.githubusercontent.com/68785729/169635214-08959724-e79c-49e6-ba47-128818d7d24e.png)

**Comment by esm7** [comment]
Which geocoding provider are you using, the default (OSM) or Google?

**Comment by esm7** [comment]
Found the issue, will release a fix in the next few hours.

**Comment by esm7** [comment]
Fixed.
