### ISSUE TITLE
Suggestion: to add a small "x" in the query box 

### ISSUE THREAD

**Issue by Darkbluetest** [esm7/obsidian-map-view#94]
Hi

Just a simple suggestion, could it be possible to add an "x" in the query box so to be able clear it with a simple click on it, instead to select all query text and press del? Just like in the search/query box of Obsidian or the graph view filter box.

Tx

**Comment by esm7** [comment]
It's already implemented in the upcoming version, which I'm hoping to release tomorrow 🙂
