### ISSUE TITLE
Bug: "New note path" in settings not working

### ISSUE THREAD

**Issue by timtester-boop** [esm7/obsidian-map-view#97]
In the settings I can chose a disk path for new note created from the map. No matter what path I enter, new notes are always created in the root path of my vault. I tested different values, for example "folder", "\folder" or "\folder\ " - the result is always the same: The note is generated in the root path and uses the "folder"-value as a prefix of the name of the note, for example "-folder-Location added on 2022-05-31T18-43".

**Comment by esm7** [comment]
I think I didn't take into account that `\` (backslash) is a valid Windows path component.
Does `/` (forward slash) work as a temporary work-around? (that's what's used in Unix variants -- Linux and Mac)

**Comment by timtester-boop** [comment]
Unfortunately the forward slash does not work either. Tested with every variant (forward slash before the folder name, after the folder name and before and after the folder name). The result is the same as described above.

**Comment by esm7** [comment]
Will fix.

**Comment by esm7** [comment]
Should be now fixed in 2.0.5, but I couldn't test it properly (not using Windows), so would love to know how it goes.

**Comment by timtester-boop** [comment]
Works like a charm. Thanks a lot for your quick fix!
