### ISSUE TITLE
"Add Geolocation (frontmatter) to current note" reproducable failure for any location

### ISSUE THREAD

**Issue by MattWilcox** [esm7/obsidian-map-view#98]
Using "Add Geolocation (frontmatter) to current note" can fail for any location and any note when the note body contains `---`.

When using this command, the resulting output is inserted immediately before _the last occurance of a `---` in the document_.

This is wrong, and can result in the information being inserted into the body of the note instead of the frontmatter - if anyone's using that as an in-note separator.

The information should find the _second_ occurance of `---` in the note, not the last.

**Comment by MattWilcox** [comment]
Worked out what this was! Made a pull request :)

**Comment by esm7** [comment]
Thank you! :sunglasses:
